### ISSUE TITLE
is monitoring or auto abitrage trade?

### ISSUE THREAD

**Issue by onthetunnel** [bmino/binance-triangle-arbitrage#1]
Hello , can i know it just tracking all pair or can do auto trade ? Thanks!

**Comment by onthetunnel** [comment]
Thanks for reply ,  Can you code it for auto order after calc profitable pair ? Thanks You!

**Comment by bmino** [comment]
There are plans to reintroduce automated trading in the future, but for now, I'm concentrating on improving the speed at which results can be found.
