### ISSUE TITLE
Config coins exclusion

### ISSUE THREAD

**Issue by luisalrp** [bmino/binance-triangle-arbitrage#10]
If I would like to add some coins to be excluded of the triangular arbitrage, where do you think it would be the best place to perform that exclusion?

Thanks

**Comment by bmino** [comment]
Hey luisalrp, are you still looking for an answer?

**Comment by hashtagex** [comment]
Yes I would like this as well. Have an option to only run certain coins. I checked out the code but it seems we would have to integrate it to be able to list the coins in the config file?

**Comment by bmino** [comment]
I'm still not sure I know what you are requesting. Do you want to (exclude / only include) certain (symbols / tickers / triangle relationships) from being scanned?

**Comment by hashtagex** [comment]
I think only include is what I mean at least.

**Comment by bmino** [comment]
I'll see about putting something like this in the next major release. I suppose it would be a more specific way to apply this application (scanning for particulars instead of against the market as a whole)
