### ISSUE TITLE
Error: ETIMEDOUT

### ISSUE THREAD

**Issue by jackyflyer** [bmino/binance-triangle-arbitrage#12]
Hello,
I get this error when I run
``npm run live`` on a ubuntu 18.04:

> binance-triangle-arbitrage@3.4.0 live /home/pierre/Cryptos/binance-triangle
> node src/main/Main.js
> 
> Querying exchangeInfo
> Expect 38 seconds to open 375 depth websockets.
> /home/pierre/Cryptos/binance-triangle/node_modules/node-binance-api/node-binance-api.js:1749
>                             if (err) throw err;
>                                      ^
> 
> Error: ETIMEDOUT
>     at Timeout._onTimeout (/home/pierre/Cryptos/binance-triangle/node_modules/request/request.js:845:19)
>     at ontimeout (timers.js:498:11)
>     at tryOnTimeout (timers.js:323:5)
>     at Timer.listOnTimeout (timers.js:290:5)
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! binance-triangle-arbitrage@3.4.0 live: `node src/main/Main.js`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the binance-triangle-arbitrage@3.4.0 live script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/pierre/.npm/_logs/2018-08-15T20_25_58_372Z-debug.log

Firstly I didn't run `brew install node` because I already had nodeJS and npm installed. Then I brewed. Both configs give this results. My api keys are in the config file. Can it be a conflict between apt-get and brew ? I also had a message about something that is not in my path during the brewing, maybe it can impact ?
Thank you

**Comment by bmino** [comment]
Hey, thanks for your interest!

I will be removing that section of the readme in the next release. It doesn't matter whether you got your NodeJS and NPM versions from brew or another location.

Which version of node and npm are you using?

**Comment by jackyflyer** [comment]
Hey, thank you fr your response ! :-)
node v8.11.3
npm 5.6.0

**Comment by bmino** [comment]
Would you delete your node_modules folder, then reinstall dependencies with `npm install` and show me the output?

**Comment by jackyflyer** [comment]
It only tells me: added 99 packages in 2.885s
And the same problem appears.

**Comment by bmino** [comment]
Update your node version to 9.x
Update your npm version to 6.x with `npm install -g npm`

I don't see anything in the stack trace provided to point to a specific cause. Perhaps there is a feature being used which isn't supported by your node version. The project was built with node 9.x so updating it will resolve that issue.

**Comment by jackyflyer** [comment]
Now I have node v9.11.2 and npm 6.4.0 but still it does not work.
I will try on windows.

**Comment by jackyflyer** [comment]
Hooo, it works now on my ubuntu 18.04. Great :-)

**Comment by bmino** [comment]
I'm glad its working for you now! Unfortunately I haven't found the root of your issue. I have gotten timeout errors recently playing around with some new features. In my case, they stem from scanning for arbitrage too soon before the internal depth caches are populated.

Fix:
Increase `DEPTH_OPEN_INTERVAL` from the default of 100 to something like 300

**Comment by jackyflyer** [comment]
Alright, I'll keep this tip in mind if that apprears again. Thank you

**Comment by ketzah** [comment]
Sorry to necropost, but I was able to resolve this error by changing my nameservers to google's 8.8.8.8 and 8.8.4.4
