### ISSUE TITLE
How to use Whiteliste?

### ISSUE THREAD

**Issue by Fungraphic** [bmino/binance-triangle-arbitrage#122]
Hi,
I tested writing like this.
"WHITELIST": [ "WETH", "AAVE", "USDC", "WNXM" ]
This is a mistake.
What is the syntax for the whitelist?
Thanks

**Comment by bmino** [comment]
This syntax is correct!
However, "WETH" does not currently trade on Binance and will cause you issues

**Comment by Fungraphic** [comment]
Oups ok thanks
But I get an error if I configure like this.
I also have another problem if I put:
    "EXECUTION": {
        "ENABLED": true,
The bot does not start.
if I put false it starts.
![Capture d’écran_2020-12-03_16-11-19](https://user-images.githubusercontent.com/26345101/101048784-37e9f700-3583-11eb-9485-033ec080cbbf.png)

**Comment by Fungraphic** [comment]
I also have another problem if I put:
    "EXECUTION": {
        "ENABLED": true,
The bot does not start.
if I put false it starts.
![1Capture d’écran_2020-12-03_16-39-29](https://user-images.githubusercontent.com/26345101/101052147-9369b400-3586-11eb-9da1-990c2b874c7c.png)

**Comment by bmino** [comment]
Interesting. The bot fails when trying to retrieve a snapshot of your current account balances. Looks like an uncaught error from cloudfront? But I don't see the actual error message.

This probably warrants highlights some missing error handling in the bot
