### ISSUE TITLE
ELIFECYLCLE error when execution is true

### ISSUE THREAD

**Issue by DanJav** [bmino/binance-triangle-arbitrage#124]
Hey!

So I'm running into ELIFECYCLE errors when I run with execution set to true. Anyone got any clue?

[...]
"Signature for this request is not valid.
[...]

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! binance-triangle-arbitrage@6.0.2 start: `node src/main/Main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the binance-triangle-arbitrage@6.0.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:

In the binance.logs the first output is
"0: "balanceData error"
    1: {}"

It then prints out a long (very long) error message, here's a snippet.

 _header: 'GET /api/v3/account?timestamp=1610378892469&recvWindow=5000&signature=ec3d1fb9e93db4b935447e42152e5a2ce1c2bf4c5aa56bd841a5c6493d117ce4 HTTP/1.1\r\n' +
      'User-Agent: Mozilla/4.0 (compatible; Node Binance API)\r\n' +
      'Content-type: application/x-www-form-urlencoded\r\n' +
      'X-MBX-APIKEY: dwjbPIrGyshiOrvzVlltdwjbPIrGyshiOrvzVlltdwjbPIrGyshiOrvzVllt\r\n' +
      'host: api.binance.com\r\n' +
      'Connection: close\r\n' +
      '\r\n',
    _keepAliveTimeout: 0,
    _onPendingData: [Function: noopPendingOutput],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object],
      requests: {},
      sockets: [Object],
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'fifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    socketPath: undefined,
    method: 'GET',
    maxHeaderSize: undefined,
    insecureHTTPParser: undefined,
    path: '/api/v3/account?timestamp=1610378892469&recvWindow=5000&signature=ec3d1fb9e93db4b935447e42152e5a2ce1c2bf4c5aa56bd841a5c6493d117ce4',
    _ended: true,
    res: [Circular *2],
    aborted: false,
    timeoutCb: [Function: emitRequestTimeout],
    upgradeOrConnect: false,
    parser: null,
    maxHeadersCount: null,
    reusedSocket: false,
    host: 'api.binance.com',
    protocol: 'https:',
    [Symbol(kCapture)]: false,
    [Symbol(kNeedDrain)]: false,
    [Symbol(corked)]: 0,
    [Symbol(kOutHeaders)]: [Object: null prototype] {
      'user-agent': [Array],
      'content-type': [Array],
      'x-mbx-apikey': [Array],
      host: [Array]
    }
  },
  request: <ref *4> Request {
    _events: [Object: null prototype] {
      error: [Function: bound ],
      complete: [Function: bound ],
      pipe: [Function (anonymous)],
      data: [Function (anonymous)],
      end: [Function (anonymous)]
    },
    _eventsCount: 5,
    _maxListeners: undefined,
    method: 'GET',
    timeout: 5000,
    headers: {
      'User-Agent': 'Mozilla/4.0 (compatible; Node Binance API)',
      'Content-type': 'application/x-www-form-urlencoded',
      'X-MBX-APIKEY': 'dwjbPIrGyshiOrvzVlltdwjbPIrGyshiOrvzVlltdwjbPIrGyshiOrvzVllt'
    },
    callback: [Function (anonymous)],
    readable: true,
    writable: true,
    explicitMethod: true,
    _qs: Querystring {
      request: [Circular *4],
      lib: [Object],
      useQuerystring: undefined,
      parseOptions: {},
      stringifyOptions: {}
    },
    _auth: Auth {
      request: [Circular *4],
      hasAuth: false,
      sentAuth: false,
      bearerToken: null,
      user: null,
      pass: null
    },
    _oauth: OAuth { request: [Circular *4], params: null },
    _multipart: Multipart {
      request: [Circular *4],
      boundary: '37deb597-5708-4d17-a5a7-7db093d08611',
      chunked: false,
      body: null
    },
    _redirect: Redirect {
      request: [Circular *4],
      followRedirect: true,
      followRedirects: true,
      followAllRedirects: false,
      followOriginalHttpMethod: false,
      allowRedirect: [Function (anonymous)],
      maxRedirects: 10,
      redirects: [],
      redirectsFollowed: 0,
      removeRefererHeader: false
    },
    _tunnel: Tunnel {
      request: [Circular *4],
      proxyHeaderWhiteList: [Array],
      proxyHeaderExclusiveList: []
    },
    setHeader: [Function (anonymous)],
    hasHeader: [Function (anonymous)],
    getHeader: [Function (anonymous)],
    removeHeader: [Function (anonymous)],
    localAddress: undefined,
    pool: {},
    dests: [],
    __isRequestRequest: true,
    _callback: [Function (anonymous)],
    uri: Url {
      protocol: 'https:',
      slashes: true,
      auth: null,
      host: 'api.binance.com',
      port: null,
      hostname: 'api.binance.com',
      hash: null,
      search: '?timestamp=1610378892469&recvWindow=5000&signature=ec3d1fb9e93db4b935447e42152e5a2ce1c2bf4c5aa56bd841a5c6493d117ce4',
      query: 'timestamp=1610378892469&recvWindow=5000&signature=ec3d1fb9e93db4b935447e42152e5a2ce1c2bf4c5aa56bd841a5c6493d117ce4',
      pathname: '/api/v3/account',
      path: '/api/v3/account?timestamp=1610378892469&recvWindow=5000&signature=ec3d1fb9e93db4b935447e42152e5a2ce1c2bf4c5aa56bd841a5c6493d117ce4',
      href: 'https://api.binance.com/api/v3/account?timestamp=1610378892469&recvWindow=5000&signature=ec3d1fb9e93db4b935447e42152e5a2ce1c2bf4c5aa56bd841a5c6493d117ce4'
    },
    proxy: null,
    tunnel: true,
    setHost: true,
    originalCookieHeader: undefined,
    _disableCookies: true,
    _jar: undefined,
    port: 443,
    host: 'api.binance.com',
    url: Url {
      protocol: 'https:',
      slashes: true,
      auth: null,
      host: 'api.binance.com',
      port: null,
      hostname: 'api.binance.com',
      hash: null,
      search: '?timestamp=1610378892469&recvWindow=5000&signature=ec3d1fb9e93db4b935447e42152e5a2ce1c2bf4c5aa56bd841a5c6493d117ce4',
      query: 'timestamp=1610378892469&recvWindow=5000&signature=ec3d1fb9e93db4b935447e42152e5a2ce1c2bf4c5aa56bd841a5c6493d117ce4',
      pathname: '/api/v3/account',
      path: '/api/v3/account?timestamp=1610378892469&recvWindow=5000&signature=ec3d1fb9e93db4b935447e42152e5a2ce1c2bf4c5aa56bd841a5c6493d117ce4',
      href: 'https://api.binance.com/api/v3/account?timestamp=1610378892469&recvWindow=5000&signature=ec3d1fb9e93db4b935447e42152e5a2ce1c2bf4c5aa56bd841a5c6493d117ce4'
    },
    path: '/api/v3/account?timestamp=1610378892469&recvWindow=5000&signature=ec3d1fb9e93db4b935447e42152e5a2ce1c2bf4c5aa56bd841a5c6493d117ce4',
    httpModule: {
      Agent: [Function: Agent],
      globalAgent: [Agent],
      Server: [Function: Server],
      createServer: [Function: createServer],
      get: [Function (anonymous)],
      request: [Function (anonymous)]
    },
    agentClass: [Function: Agent],
    agent: Agent {
      _events: [Object: null prototype],
      _eventsCount: 2,
      _maxListeners: undefined,
      defaultPort: 443,
      protocol: 'https:',
      options: [Object],
      requests: {},
      sockets: [Object],
      freeSockets: {},
      keepAliveMsecs: 1000,
      keepAlive: false,
      maxSockets: Infinity,
      maxFreeSockets: 256,
      scheduling: 'fifo',
      maxTotalSockets: Infinity,
      totalSocketCount: 1,
      maxCachedSessions: 100,
      _sessionCache: [Object],
      [Symbol(kCapture)]: false
    },
    _started: true,
    href: 'https://api.binance.com/api/v3/account?timestamp=1610378892469&recvWindow=5000&signature=ec3d1fb9e93db4b935447e42152e5a2ce1c2bf4c5aa56bd841a5c6493d117ce4',
    req: <ref *3> ClientRequest {
      _events: [Object: null prototype],
      _eventsCount: 6,
      _maxListeners: undefined,
      outputData: [],
      outputSize: 0,
      writable: true,
      destroyed: false,
      _last: true,
      chunkedEncoding: false,
      shouldKeepAlive: false,
      _defaultKeepAlive: true,
      useChunkedEncodingByDefault: false,
      sendDate: false,
      _removedConnection: false,
      _removedContLen: false,
      _removedTE: false,
      _contentLength: 0,
      _hasBody: true,
      _trailer: '',
      finished: true,
      _headerSent: true,
      socket: [TLSSocket],
      _header: 'GET /api/v3/account?timestamp=1610378892469&recvWindow=5000&signature=ec3d1fb9e93db4b935447e42152e5a2ce1c2bf4c5aa56bd841a5c6493d117ce4 HTTP/1.1\r\n' +
        'User-Agent: Mozilla/4.0 (compatible; Node Binance API)\r\n' +
        'Content-type: application/x-www-form-urlencoded\r\n' +
        'X-MBX-APIKEY: dwjbPIrGyshiOrvzVlltdwjbPIrGyshiOrvzVlltdwjbPIrGyshiOrvzVllt\r\n' +
        'host: api.binance.com\r\n' +
        'Connection: close\r\n' +
        '\r\n',
      _keepAliveTimeout: 0,
      _onPendingData: [Function: noopPendingOutput],
      agent: [Agent],
      socketPath: undefined,
      method: 'GET',
      maxHeaderSize: undefined,
      insecureHTTPParser: undefined,
      path: '/api/v3/account?timestamp=1610378892469&recvWindow=5000&signature=ec3d1fb9e93db4b935447e42152e5a2ce1c2bf4c5aa56bd841a5c6493d117ce4',
      _ended: true,
      res: [Circular *2],
      aborted: false,
      timeoutCb: [Function: emitRequestTimeout],
      upgradeOrConnect: false,
      parser: null,
      maxHeadersCount: null,
      reusedSocket: false,
      host: 'api.binance.com',
      protocol: 'https:',
      [Symbol(kCapture)]: false,
      [Symbol(kNeedDrain)]: false,
      [Symbol(corked)]: 0,
      [Symbol(kOutHeaders)]: [Object: null prototype]
    },
    ntick: true,
    timeoutTimer: null,
    response: [Circular *2],
    originalHost: 'api.binance.com',
    originalHostHeaderName: 'host',
    responseContent: [Circular *2],
    _destdata: true,
    _ended: true,
    _callbackCalled: true,
    [Symbol(kCapture)]: false
  },
  toJSON: [Function: responseToJSON],
  caseless: Caseless {
    dict: {
      'content-type': 'application/json;charset=UTF-8',
      'content-length': '63',
      connection: 'close',
      date: 'Mon, 11 Jan 2021 15:28:12 GMT',
      server: 'nginx',
      'x-mbx-uuid': '4b32ddd2-7603-45bc-8dfc-3bd1df8c4fb8',
      'x-mbx-used-weight': '16',
      'x-mbx-used-weight-1m': '16',
      'strict-transport-security': 'max-age=31536000; includeSubdomains',
      'x-frame-options': 'SAMEORIGIN',
      'x-xss-protection': '1; mode=block',
      'x-content-type-options': 'nosniff',
      'content-security-policy': "default-src 'self'",
      'x-content-security-policy': "default-src 'self'",
      'x-webkit-csp': "default-src 'self'",
      'cache-control': 'no-cache, no-store, must-revalidate',
      pragma: 'no-cache',
      expires: '0',
      'x-cache': 'Error from cloudfront',
      via: '1.1 12ab600b22d5c2eb1f2192b1156c2fd1.cloudfront.net (CloudFront)',
      'x-amz-cf-pop': 'AMS50-C1',
      'x-amz-cf-id': 'ct-K6MdhUr9tvimX1Ithg7qqD2esAhZD0-WtoYFljspKuAqCgpqYYw=='
    }
  },
  body: '{"code":-1022,"msg":"Signature for this request is not valid."}',
  [Symbol(kCapture)]: false,
  [Symbol(RequestTimeout)]: undefined
}

**Comment by DanJav** [comment]
Fixed the error by generating a new API key

**Comment by ScuzzyHoulihan** [comment]
What was the resolution?
