### ISSUE TITLE
Massive negative profit thresholds appearing

### ISSUE THREAD

**Issue by jkollin14** [bmino/binance-triangle-arbitrage#128]
Hey thanks for opening this up, this is awesome! 

I tried setting the script up and I found an interesting situation where reflexive coin pairs both had massively negative profits. I was just running in on test mode, but it is something that I cant figure out. My logic is that if it was that massively negative you would be able to profit the other way. Any idea why this would be happening? For the test case even with no fee, it cant seem to find arbitrage opportunities.

Also, for reference, the server I am running on is in Toyko and is running at a latency of about 20ms.

![image](https://user-images.githubusercontent.com/17691189/105652941-8d0dff00-5e88-11eb-8993-844e7af9b754.png)

```
"INVESTMENT": {
        "BASE": "BTC",
        "MIN": 0.00001,
        "MAX": 0.001,
        "STEP": 0.00001
    },
    "SCANNING": {
        "DEPTH": 10,
        "WHITELIST": ["TUSD", "BTC", "LTC", "ETH"]
    },
    "EXECUTION": {
        "ENABLED": false,
        "CAP": 0,
        "STRATEGY": "linear",
        "TEMPLATE": ["*", "*", "*"],
        "FEE": 0.000,
        "THRESHOLD": {
            "PROFIT": 0.00,
            "AGE": 25
        }
    },
```

**Comment by bmino** [comment]
Hey! Yup ABC isn't identical to CBA because of the order books. Going in one direction might utilize the bids of AB and then going in reverse would utilize the asks of AB or vice versa

**Comment by bmino** [comment]
Feel free to open a new issue for any problems/questions you encounter!
