### ISSUE TITLE
"ETIMEDOUT" Receive window 5000-1000000

### ISSUE THREAD

**Issue by ExtraLime** [bmino/binance-triangle-arbitrage#129]
I'm receiving this error code when I `npm start`.

here is the output:

Checking configuration ...
Checking latency ...
Experiencing 215 ms of latency
Fetching exchange info ...
Found 927/1273 currently trading tickers
Found 504 triangular trades
Checking market conditions ...
Opening 698 depth websockets for 698 tickers ...
Error: ETIMEDOUT
    at Timeout.<anonymous> (gits/binance-triangle-arbitrage/node_modules/request/request.js:848:19)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7) {
  code: 'ETIMEDOUT',
  connect: true
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! binance-triangle-arbitrage@6.1.0 start: `node src/main/Main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the binance-triangle-arbitrage@6.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /.npm/_logs/2021-01-31T21_38_56_124Z-debug.log

here is my config:
{

    "KEYS": {
        "API": "",
        "SECRET": ""
    },

    "INVESTMENT": {
        "BASE": "USDT",
        "MIN": 0.010,
        "MAX": 0.015,
        "STEP": 0.005
    },

    "SCANNING": {
        "DEPTH": 50,
        "WHITELIST": []
    },

    "EXECUTION": {
        "ENABLED": false,
        "CAP": 1,
        "STRATEGY": "linear",
        "TEMPLATE": ["BUY", "SELL", "SELL"],
        "FEE": 0.075,
        "THRESHOLD": {
            "PROFIT": 0.00,
            "AGE": 200000
        }
    },

    "HUD": {
        "ENABLED": true,
        "ROWS": 10,
        "REFRESH_RATE": 500
    },

    "LOG": {
        "LEVEL": "debug",
        "PRETTY_PRINT": true,
        "STATUS_UPDATE_INTERVAL": 2
    },

    "WEBSOCKET": {
        "BUNDLE_SIZE": 1,
        "INITIALIZATION_INTERVAL": 200
    },

    "TIMING": {
        "RECEIVE_WINDOW": 10000
    },

    "BINANCE_OPTIONS": {}

}

ubuntu 20
vpn with german ip and true US ip

I read through some of the other issues and tried a few different things in the config file. This is the only error I have received.   The error says its coming from the request package but before I dig into it, any ideas?

**Comment by bmino** [comment]
It happens. The app is making quite a few requests and they can get tied up.

Some ideas to play around with:
* Increase the `WEBSOCKET.INITIALIZATION_INTERVAL` to something a lil higher to space out the connections
* Use a whitelist to narrow the pool of tickers being tracked

Idk what `TIMING.RECEIVE_WINDOW` is doing? That isn't a valid config option. Make sure you are using the latest release of the app. You can accomplish what I think you are trying to do like this:
```
"BINANCE_OPTIONS": {
    "recvWindow": 10000
}
```

**Comment by ExtraLime** [comment]
![image](https://user-images.githubusercontent.com/37124296/106473652-dfd35200-6458-11eb-9b71-7aeccc53992c.png)
My bad, i just saw this on another issue from august. But great thank you for the info. Ill try now.

**Comment by bmino** [comment]
Hey I appreciate you looking through issues for some self help :)
I'll leave this open as you troubleshoot through. Lemme know what happens

**Comment by ExtraLime** [comment]
Thanks. I know it get annoyed when people say "it doesnt work" without reading ANYTHING.
I managed for it to not error out, by changing the recvWindow and using BTC as the currency (did not need to whitelist). Thanks. 
I have a super noob question about where to get to the hud. I more of a python guy, and when I do webdev its usually in React or some other spoon fed frame work. After looking through the code, I still cant determines what how to bring up the HUD. Any help with this would be great thanks.

**Comment by bmino** [comment]
The HUD will display in the same terminal window that you started the app with (`npm start`). Make sure the app is actually running. You will see an output of "Initialized" in the terminal after all websockets have been initialized which will take longer depending on your INITIALIZATION_INTERVAL

**Comment by m4s0** [comment]
same problem of happen to me

`
$ npm start


> binance-triangle-arbitrage@6.1.0 start /code/languages/node.js/binance-triangle-arbitrage
> node src/main/Main.js

Checking configuration ...
Checking latency ...
Error: ETIMEDOUT
    at Timeout.<anonymous> (/code/languages/node.js/binance-triangle-arbitrage/node_modules/request/request.js:848:19)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  code: 'ETIMEDOUT',
  connect: true
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! binance-triangle-arbitrage@6.1.0 start: `node src/main/Main.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the binance-triangle-arbitrage@6.1.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/m4s0/.npm/_logs/2021-02-01T22_58_06_651Z-debug.log
`

**Comment by m4s0** [comment]
I solved chaning this part of conf

```
  "WEBSOCKET": {
    "BUNDLE_SIZE": 3,
    "INITIALIZATION_INTERVAL": 1000
  },
  "BINANCE_OPTIONS": {
    "recvWindow": 10000
  }
```

**Comment by ExtraLime** [comment]
I was able to run it, but it took so long i just stepped away, so maybe i missed the HUD. It finished running and displayed the trade it would have executed. But the next time it timed out again. I think because im on a VPN the latency is too high. I am going to re run with a few different configurations and different VPN locations to see if I can get it to execute successively.  I would consider my issue closable. @m4s0 you good?

**Comment by m4s0** [comment]
@ExtraLime using a VPN is not a good idea IMHO

**Comment by ExtraLime** [comment]
Yeah I agree, but i have my reasons. Im going to go ahead and close this ticket.

**Comment by ExtraLime** [comment]
@bmino kicked you some scratch for this. Good stuff man
