### ISSUE TITLE
Ability to set fees based on specific trading pairs

### ISSUE THREAD

**Issue by seanorama** [bmino/binance-triangle-arbitrage#134]
Some trading pairs have a different Marker Fee.

For example, currently all GBP pairs have Zero Maker Fee: https://www.binance.com/en/support/announcement/1928d02e3a6444cb8b8a13b0aa33307a

So in addition to the base fee, overrides could look something like this:
```
{ "FEE":"0.00", "PAIRS":[ "XRPGBP", "GBPUSDT", "GBPBUSD", "SXPGBP", "LINKGBP", "BNBGBP", "ETHGBP", "BTCGBP" ] },
```

**Comment by bmino** [comment]
This is an excellent point and is not currently supported. I've seen this happen before and will likely happen again for various reasons.

Ideally there is an endpoint (per user key) that will give fees per ticker. If so, we can avoid having users configure trade fees altogether which would be great!

**Comment by Utone** [comment]
Same goes for any non crypto FIAT AUD, EUR etc the *money inflow pairs.
And...: BUSD! also ZERO fee Maker (not if executed at market but can often selling COIN gets a better price on BUSD vs USDT or GBP..etc
All Quote should be compared after conversion to reference currency
But buy my BUSD low so extra BUSD vs less USDT/C etc is ~ same as USD XD
*[Take note these ALL money gateway markets EUR/USDT GBP/USDC ETC (get a volatility tax..)
Very 'unstable'  when retail deposits come in. does present some nice opportunities 
But do it with your verified account so you don't get stuck with a FIAT bag 
Make notes on rated paid for 'stable'  ]

**Comment by bmino** [comment]
I did some searching and could not find an official endpoint with standard data around fees :(

**Comment by Etrusques** [comment]
Would you consider coding for cross-exchange arbitrage opportunities ? The more exchanges the better, right? Also, have you considered using DEXs instead? Interacting directly with the blockchain is so cool. Thanks for the bot bmino.

**Comment by paulwongx** [comment]
> Would you consider coding for cross-exchange arbitrage opportunities ? The more exchanges the better, right? Also, have you considered using DEXs instead? Interacting directly with the blockchain is so cool. Thanks for the bot bmino.

Maybe I'm expressing bmino's opinions or maybe I'm not... but what is the the original authors incentive to make this better and better to add more exchanges? I would think if someone else were to contribute to the project and add more exchanges then that makes sense... ? Unless this is for some resume padding or something...

My apologies in advance as this comment adds no value. lol

**Comment by bmino** [comment]
Hey yall! I put this public a few years ago as I was developing the concept to get some opinions and assistance. I don't personally use this project anymore so this is just support. There aren't plans to add any new features currently

**Comment by Etrusques** [comment]
Alright then.
Cool project anyhow.
Thanks Brandon
