### ISSUE TITLE
code base is realy ugly.

### ISSUE THREAD

**Issue by Amenocy** [bmino/binance-triangle-arbitrage#135]
there is no even one line of comment :|

**Comment by ashwinvandijk** [comment]
I'm sure @bmino is open to pull requests.

**Comment by bmino** [comment]
What are you struggling to understand? There are indeed comments in a few places but I used naming conventions where possible to avoid comments.

There is also generalized documentation and extensive config documentation

**Comment by bmino** [comment]
I'm closing this lol
