### ISSUE TITLE
Window does not display anything, despite HUD being True

### ISSUE THREAD

**Issue by Spuddya7x** [bmino/binance-triangle-arbitrage#136]
HUD is set to true, and all i can see is what looks like an r in the top left corner. The rest of the GUI/HUD isnt being drawn. 

![image](https://user-images.githubusercontent.com/48963293/107997542-e7f3cb80-6fda-11eb-8413-94ff3ca97948.png)

**Comment by bmino** [comment]
Mmm looks like git bash does not support the library we use to display a rapidly updating table (blessed).
The standard windows command prompt seems to support the HUD fine

**Comment by Spuddya7x** [comment]
Oh! I'm fairly new to this, so forgive me. I can just open windows
powershell and run the same commands? I'll try that later today.

**Comment by bmino** [comment]
Just tested on windows powershell and it works for me!
Lemme know what your experience is

**Comment by Spuddya7x** [comment]
It works in windows powershell. Thanks very much for your help. Ill just use Powershell from now on. Its nice on a blue background!
