### ISSUE TITLE
too shallow to convert

### ISSUE THREAD

**Issue by NumairAwan** [bmino/binance-triangle-arbitrage#138]
I am trying to run it but keeps getting this error, I also increase the depth to 1000 and add the 
"USDT","CAKE","ONE","ETC","BTC","BUSD","BNB"
 in the whitelist but same error in performence.log.

I am using USDT as base coin.

**Comment by bmino** [comment]
Please post the full error message. I am assuming you get:
`... depth (0) too shallow to convert ...`

which typically means your cpu is being overwhelmed and the websockets are timing out

**Comment by NumairAwan** [comment]
Yes 
`... depth (0) too shallow to convert ...`
error but my cpu usage is normal (below 70%) and if the problem is websockets are timing out then how can i fix this?
I am using VPS 12 cores and 24GB ram.

**Comment by sergeykhliustin** [comment]
Hi! I want to note the same issue, sockets always timeout and disconnecting. But when looking on htop command, seems like one core is around 100%, but others are not busy (8 cpu total)

**Comment by NumairAwan** [comment]
The bot is running for the last 24 hours but didn't even execute the 1 trade all just getting `... depth (0) too shallow to convert ...`
here I am sharing my config.json let me know if I am doing something wrong.

[config.txt](https://github.com/bmino/binance-triangle-arbitrage/files/6041973/config.txt)

**Comment by bmino** [comment]
Yup, this isn't utilizing multiple threads so your cpu usage might say 10% usage, but one of your 8 threads is maxed out performing calculations. The app logging is watching for clock time being eaten up for calculations and will now warn you when this is too high at every status update interval

**Comment by k4m4h4l** [comment]
[3/4/2021, 12:00:51 PM] [34mDEBUG[39m: [36mDepth cache updates per second:  850.90[39m
[3/4/2021, 12:00:51 PM] [34mDEBUG[39m: [36mCPU clock usage for calculations:  35.27%[39m
[3/4/2021, 12:00:51 PM] [34mDEBUG[39m: [36mAPI Latency: 255 ms[39m


only 32% Usage

I have the same problem what would be a solution to fix

**Comment by bmino** [comment]
I originally saw disconnects as that number passed 50% but issues might present themselves earlier. You can reduce the cpu intensity by decreasing `INVESTMENT.STEP` or `INVESTMENT.MAX` and other options like depth will affect this @k4m4h4l
