### ISSUE TITLE
Minimum balance

### ISSUE THREAD

**Issue by k4m4h4l** [bmino/binance-triangle-arbitrage#140]
What would be a minimum value in USD that would be profitable to operate this code, using BTC or XRP as a base?

**Comment by bmino** [comment]
Minimum balances are configured in terms of the base asset. Lower values exhaust less of the order book and will therefore use more efficient depth entries, but have less investment/profit.

The bot checks between your MIN and MAX for the most profitable position. There is no perfect MIN/MAX and that is why it's configurable. Just don't use a MIN value that is less than the base asset's minimum trading value or no orders can succeed
