### ISSUE TITLE
Run on aws

### ISSUE THREAD

**Issue by klaszlo8207** [bmino/binance-triangle-arbitrage#143]
How to install/deploy this app and then run on amazon aws?
Can you help me in details? Thanks

**Comment by bmino** [comment]
Hey! First off ensure your ec2 has enough cpu specs to handle the calculations you are throwing at it. I've settled on a spot instance of `m5n.xlarge` deployed in the tokyo region

You'd be following the same [Getting Started steps](https://github.com/bmino/binance-triangle-arbitrage#getting-started) in the readme, and running them on an EC2.

Some complications you might hit are not having git installed, and you can install that via `sudo apt-get install git` or your OS equivalent.

**Comment by ismailfatihiltar** [comment]
Hey @bmino could you share your HUD that you get from aws server which is located on tokyo region.  My starting latency ~450ms (in EU) and minimum AGE ~1800 ms.  Do  I have to change my AGE of Execution set on config file to 1800 ? ( Now it is default 25ms and ı haven't get an execution yet )

**Comment by klaszlo8207** [comment]
> 
> 
> Hey! First off ensure your ec2 has enough cpu specs to handle the calculations you are throwing at it. I've settled on a spot instance of `m5n.xlarge` deployed in the tokyo region
> 
> You'd be following the same [Getting Started steps](https://github.com/bmino/binance-triangle-arbitrage#getting-started) in the readme, and running them on an EC2.
> 
> Some complications you might hit are not having git installed, and you can install that via `sudo apt-get install git` or your OS equivalent.

Thanks

_You'd be following the same Getting Started steps in the readme,_ **and running them on an EC2.**

How can I run on EC2? Can u give me a tutorial?

Thanks

**Comment by bmino** [comment]
You should look up some tutorials on how to use VPS like AWS. Here is one link from google:
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EC2_GetStarted.html
