### ISSUE TITLE
How can I set  triangular trades?

### ISSUE THREAD

**Issue by songyu-123** [bmino/binance-triangle-arbitrage#145]
Hey, thank you for your kindness. When I run this program, I got an error called "Error: No triangular trades were identified". So I guess that's because I did a wrong identification on the whitelist.
So, what is a legal identification of a whitelist? Can you give me some examples?
    "SCANNING": {
        "DEPTH": 50,
        "WHITELIST": ["FILBNB","FILUSDT"]
    },
That's illegal, right?

**Comment by bmino** [comment]
Yup, you'll need more assets in your whitelist. At least 3 haha to make a triangle

A triangular trade is defined as three assets A, B, and C where you can:

1) Trade A for B
2) Trade B for C
3) Trade C for A

With only 2 assets in your whitelist, this is impossible

**Comment by songyu-123** [comment]
Thank you for your reply. I would like to ask you a few more questions:
1. When I select "Linear" in EXECUTION.STRATEGY, there is no need to set a whitelist. When I select "parallel" in EXECUTION.STRATEGY, I need to set a whitelist. What is the principle? And is the content of the whitelist similar to a trading pair like "BNBUSDT" or a cryptocurrency like "BNB"?
2. Why the robot did not make a deal when I clearly saw an arbitrage opportunity on HUD? What should I prepare in advance for my account assets?
3. Does the estimated profit include spreads?
4. Since the order cannot be 100% synchronized, what the robot do if one of the steps in the A-B-C chain cannot be traded?

**Comment by bmino** [comment]
Take a read through the [configuration readme](https://github.com/bmino/binance-triangle-arbitrage/tree/master/config) for more info.

1) Linear vs. parallel is explained in the [extended documentation](https://github.com/bmino/binance-triangle-arbitrage/blob/master/src/resources/docs/strategies.md). The whitelist should include individual assets like "BNB" and "USDT".
2) My guess is that your age threshold was not satisfied so the robot appropriately did not make any trades.
3) The estimated profit uses math directly from the order book so spreads are accounted for.
4) I'm not sure what you mean by synchronized?

**Comment by songyu-123** [comment]
Hey, Bmino. Thank you for your response again. I'm still having trouble with real-time trading. So can you do me a favor?
![20210411223438](https://user-images.githubusercontent.com/63093855/114309185-f6f98480-9b18-11eb-8c78-0e363fca3931.png)
[config.json.txt](https://github.com/bmino/binance-triangle-arbitrage/files/6292051/config.json.txt)
As you can see, I set the config file like this, and the bot ran very well. You can see on the screen there are some arbitrage opportunities, right? However, I can't see any orders made by the bot.
So, could you tell me what's wrong with my config file and what may cause this question?
By the way, what is the real meaning of "AGE"? I can't get the point.

**Comment by bmino** [comment]
Great, thanks for posting the HUD. As I suspected, your ages are huge. Read the config readme for more details, but the age values are how old each piece of data is. You wouldn't want to trade with data that is 4 second old right? And probably not with data that is even 200ms old

**Comment by bmino** [comment]
Looks like most of those entries are 168 seconds old! Since the value is given in milliseconds

**Comment by songyu-123** [comment]
Thank you for your help, again.
I adjusted the parameter like this:
"THRESHOLD": {
            "PROFIT": 0.1,
            "AGE": 250
        }
And I saw the HUD like this:
![微信图片_20210412125813](https://user-images.githubusercontent.com/63093855/114342812-22b75180-9b8f-11eb-80d9-0d753be22665.png)
From my point, it would trade BUSD-ANT-BTC.
However, it still didn't trade.
So, what's the problem for now?

**Comment by bmino** [comment]
You are correct. What version of the app are you using? The most recent version displays Age in milliseconds, but your HUD appears to be displaying Age in seconds

**Comment by bmino** [comment]
I suspect you have an older version of the app, and you have specified an age threshold of 250 ms, but the HUD is showing 168 seconds so no trade was sent (correctly)

**Comment by songyu-123** [comment]
Thanks for replying. I'm going to update the app version and run it again.
I'll tell you if it makes orders.
Thank you.
My Email:zzh65895761@gmail.com
Keep connecting :)

**Comment by bmino** [comment]
go ahead and open up a new issue if you experience more problems, gonna close this due to inactivity
