### ISSUE TITLE
order stuck

### ISSUE THREAD

**Issue by onthetunnel** [bmino/binance-triangle-arbitrage#15]
hello , i running the execute branch , and using btc for trade , and the bot use btc buy eth and use eth buy altcoin and no sell it to btc , hope you can solve it , Thanks!

**Comment by bmino** [comment]
Hey, thanks for your interest!

There should definitely be three trades as you mentioned. Are you trading using the parallel or linear execution strategy?

Also, could you post the logs generated?

**Comment by bmino** [comment]
Please post the files listed under the `/log` directory:

* `execution.log`
* `performance.log`

Also helpful would be your `/config/config.js` file but EXCLUDE YOUR API KEY AND SECRET!

**Comment by bmino** [comment]
Are you still experiencing this issue? If so, please post the information I requested above when the scenario occurs.

My suspicion is that you did not have a high enough balance of the altcoin initially and that third transaction failed due to the insignificant balance.
