### ISSUE TITLE
ETIMEDOUT and proxy server.

### ISSUE THREAD

**Issue by sdn9002** [bmino/binance-triangle-arbitrage#150]
Can I use this tool behind a proxy server?
I'm receiving "Error: ETIMEDOUT" on "Checking latency ..." step.
I'm using default configuration. I've also tried to set SCANNING.WHITELIST, but the result is the same - "Error: ETIMEDOUT".

D:\binance-triangle-arbitrage-6.2.0>npm start

> binance-triangle-arbitrage@6.2.0 start D:\binance-triangle-arbitrage-6.2.0
> node src/main/Main.js

Checking configuration ...
Checking latency ...
Error: ETIMEDOUT
    at Timeout.<anonymous> (D:\binance-triangle-arbitrage-6.2.0\node_modules\request\request.js:848:19)
    at listOnTimeout (internal/timers.js:554:17)
    at processTimers (internal/timers.js:497:7) {
  code: 'ETIMEDOUT',
  connect: true
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! binance-triangle-arbitrage@6.2.0 start: `node src/main/Main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the binance-triangle-arbitrage@6.2.0 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\xxxxxx\AppData\Roaming\npm-cache\_logs\2021-04-19T12_27_42_529Z-debug.log

D:\binance-triangle-arbitrage-6.2.0>

**Comment by bmino** [comment]
I have not implemented any support specifically for using a proxy mainly because any middleware introduces unwanted latency in such a time-sensitive process.

Your run failed when making a single request for server time. This happens before any websockets are initiated or depth cache requests are made. Pretty odd since that is not demanding. Are you rate limited?

**Comment by bmino** [comment]
I've gotten that maybe twice in my whole time dev'ing this. I restarted the bot and chalked it up to a network fluke

**Comment by sdn9002** [comment]
Thank you for your response.
I'm not rate/speed limited. I'm behind an enterprise proxy server on work machine, otherwise I can't connect to the internet.
I've tried the tool on my home machine (not behind proxy server) and there are negative numbers for age column.

**Comment by bmino** [comment]
That work proxy might not like requests being made out to Tokyo haha. As for the negative age numbers, my first thought is a syncing issue with your local time. Can you resync to a time server and retry?

**Comment by ScuzzyHoulihan** [comment]
Anyone find a solution to this issue? Having this issue once I set execution value to true.
