### ISSUE TITLE
Age grows and grows as time passes

### ISSUE THREAD

**Issue by gaffelosked** [bmino/binance-triangle-arbitrage#151]
Tried changing config step by step, no change. Getting loads of 'Bid depth (0) too shallow to convert' even for very small amounts like 10 EUR to XRP

![image](https://user-images.githubusercontent.com/22619458/115275301-e7de8c00-a141-11eb-882b-fb426c5c6812.png)

`"INVESTMENT": {
        "EUR": {
		 "MIN": 10, 
		 "MAX": 4500,
		 "STEP": 10
    }
    },

    "SCANNING": {
        "DEPTH": 100,
        "WHITELIST": []
    },

    "EXECUTION": {
        "ENABLED": false,
        "CAP": 1,
        "STRATEGY": "linear",
        "TEMPLATE": ["BUY", "SELL", "SELL"],
        "FEE": 0.075,
        "THRESHOLD": {
            "PROFIT": 0.01,
            "AGE": 25
        }
    },

    "HUD": {
        "ENABLED": true,
        "ROWS": 10,
        "REFRESH_RATE": 200
    },

    "LOG": {
        "LEVEL": "debug",
        "PRETTY_PRINT": true,
        "STATUS_UPDATE_INTERVAL": 2
    },

    "WEBSOCKET": {
        "BUNDLE_SIZE": 1,
        "INITIALIZATION_INTERVAL": 10
    },

    "BINANCE_OPTIONS": {}`

**Comment by gaffelosked** [comment]
CPU clock usage for calculations:  98.36%, probably my CPU which is an AMD Ryzen 5 5600X, will try on server.

**Comment by bmino** [comment]
You have a big range of min to max investment with a small step size. This means many calculations must be done each cycle and will really tax your cpu
