### ISSUE TITLE
Layman step by step to install

### ISSUE THREAD

**Issue by Granzeto** [bmino/binance-triangle-arbitrage#153]
Hello, I'm a layman in programming, but if someone can help me by doing a step by step, I would be very happy.

The program that I must open, the commands that I must execute, I just need these initial information.

Thank you

**Comment by bmino** [comment]
Hey, glad to see you interested!

A great read to start would be the project's readme file.
You can find it on the home page here: https://github.com/bmino/binance-triangle-arbitrage#readme
