### ISSUE TITLE
Has anyone made a profit using this method?

### ISSUE THREAD

**Issue by novaextent** [bmino/binance-triangle-arbitrage#155]

**Comment by KrysThyFysh** [comment]
I just set it up an hour ago and I've seen opportunities where there was a possible trade to take place but there was none ever placed, I'm gonna wait another 12-24 hours before I ask questions to see if it's working properly or not

**Comment by bmino** [comment]
The bot will execute a trade that matches your specified parameters. Make sure you understand what they mean by reading the [readme](https://github.com/bmino/binance-triangle-arbitrage/tree/master/config)
