### ISSUE TITLE
How to reduce the age

### ISSUE THREAD

**Issue by KrysThyFysh** [bmino/binance-triangle-arbitrage#156]
So I've realized the reason it hasn't been taking any trades is because of the age of the opportunities are all older, so what in the config would I have to change to get more recent ages, websocket is 200 ms, and HUD is 500 ms
![image](https://user-images.githubusercontent.com/83042881/115799365-5885e280-a3a6-11eb-89a6-f7bcc2e7f49b.png)
or would I up the threshold?

**Comment by bmino** [comment]
Please read the configuration [readme ](https://github.com/bmino/binance-triangle-arbitrage/tree/master/config) to better understand what those values mean. Neither of which will affect your AGE values. The best thing you can do is locate your bot to be running as physically close to Binance's servers as possible. If you don't know how to do this, try the Tokyo region

**Comment by KrysThyFysh** [comment]
Ohhh okay I understand now, I read the documentation for in the readme and it's clarified a lot of things for me, thank you

**Comment by bmino** [comment]
Coolbeans, feel free to open up a new issue if you have one
