### ISSUE TITLE
Limit Order

### ISSUE THREAD

**Issue by scaranti** [bmino/binance-triangle-arbitrage#158]
Hello, how is everything ? I'm using the bot, and the executions are OK. However, we have the issue of price slips. A solution would be to execute the limit order instead of the Market Order, would it be possible? Is that configurable?

Thanks

**Comment by bmino** [comment]
Yup it's possible haha, but that would be some dev work to essentially rework the bot. A potentially easier path would be using the parallel execution and replacing the calls with limit orders instead of market orders and that wouldn't be so much refactoring
