### ISSUE TITLE
Ask depth (0) too shallow 

### ISSUE THREAD

**Issue by jp054** [bmino/binance-triangle-arbitrage#159]
Hi ! :)
Firstly, thanks for sharing. 
The bot works but does not make any transactions. I have the following messages :

[30/04/2021, 15:31:42] WARN: Ask depth (0) too shallow to convert 10 USDT to MATIC using MATICUSDT
....
[30/04/2021, 15:46:10] WARN: Ask depth (1) too shallow to convert 0.7530999999999999 USDT to HOT using HOTUSDT
...
Any ideas ? I can't find the reason for my problem.
I tested different values ​​of 'DEPTH' and added a whitelist. I have a good network connection...
....

Performance.log :
![image](https://user-images.githubusercontent.com/34319814/116729414-6ad7d000-a9e7-11eb-86c6-2e8e6a22ee23.png)

Execution.log :
![image](https://user-images.githubusercontent.com/34319814/116729258-3d8b2200-a9e7-11eb-889d-127de2c3032e.png)

Binance.log :
![image](https://user-images.githubusercontent.com/34319814/116729534-90fd7000-a9e7-11eb-8e1b-c6e2c7e716c0.png)

Config.json :
"KEYS": {
        "API": "",
        "SECRET": ""
    },

    "INVESTMENT": {
        "USDT": {
            "MIN": 10,
            "MAX": 20,
            "STEP": 1
        }
    },

    "SCANNING": {
        "DEPTH": 10,
        "WHITELIST": ["USDT","BTC","MATIC","BUSD","ONE","HOT","BRL","BTT","TRX","WIN","BNB","XLM","DAI","YFI","DOGE","STRAX"]
    },

    "EXECUTION": {
        "ENABLED": true,
        "CAP": 0,
        "STRATEGY": "linear",
        "TEMPLATE": ["BUY", "SELL", "SELL"],
        "FEE": 0.075,
        "THRESHOLD": {
            "PROFIT": 1,
            "AGE": 300
        }
    },

    "HUD": {
        "ENABLED": true,
        "ROWS": 30,
        "REFRESH_RATE": 500
    },

    "LOG": {
        "LEVEL": "debug",
        "PRETTY_PRINT": true,
        "STATUS_UPDATE_INTERVAL": 2
    },

    "WEBSOCKET": {
        "BUNDLE_SIZE": 1,
        "INITIALIZATION_INTERVAL": 100
    },

    "BINANCE_OPTIONS": {}

}

**Comment by bmino** [comment]
Great, thanks for providing so much relevant info! I think you are having a different symptom than most people who experience this. I only see this with one pair. Likely the pair had a couple bids or asks removed/exhausted faster than new ones were added. Increase your DEPTH value to something higher like 50
