### ISSUE TITLE
error Failed at the binance-triangle-arbitrage@6.2.0 start script.

### ISSUE THREAD

**Issue by ScuzzyHoulihan** [bmino/binance-triangle-arbitrage#164]
Failing when I set my execution to true. Can populate chart with data fine when it's on false. I put the error log below. Anyone have any clues with data below?
--------------------------------------------------------------------------------------------------------------

0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.14.10
3 info using node@v14.15.4
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle binance-triangle-arbitrage@6.2.0~prestart: binance-triangle-arbitrage@6.2.0
6 info lifecycle binance-triangle-arbitrage@6.2.0~start: binance-triangle-arbitrage@6.2.0
7 verbose lifecycle binance-triangle-arbitrage@6.2.0~start: unsafe-perm in lifecycle true
8 verbose lifecycle binance-triangle-arbitrage@6.2.0~start: PATH: C:\Users\RazorRamone\AppData\Roaming\nvm\v14.15.4\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\Users\RazorRamone\binance-triangle-arbitrage-master\node_modules\.bin;C:\Python39\Scripts\;C:\Python39\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\ProgramData\chocolatey\bin;C:\Users\RazorRamone\AppData\Roaming\nvm;C:\Program Files\nodejs;C:\Users\RazorRamone\AppData\Local\Microsoft\WindowsApps;C:\Users\RazorRamone\AppData\Roaming\npm;C:\Users\RazorRamone\AppData\Roaming\nvm;C:\Program Files\nodejs
9 verbose lifecycle binance-triangle-arbitrage@6.2.0~start: CWD: C:\Users\RazorRamone\binance-triangle-arbitrage-master
10 silly lifecycle binance-triangle-arbitrage@6.2.0~start: Args: [ '/d /s /c', 'node src/main/Main.js' ]
11 silly lifecycle binance-triangle-arbitrage@6.2.0~start: Returned: code: 1  signal: null
12 info lifecycle binance-triangle-arbitrage@6.2.0~start: Failed to exec start script
13 verbose stack Error: binance-triangle-arbitrage@6.2.0 start: `node src/main/Main.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Users\RazorRamone\AppData\Roaming\nvm\v14.15.4\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Users\RazorRamone\AppData\Roaming\nvm\v14.15.4\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1048:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:288:5)
14 verbose pkgid binance-triangle-arbitrage@6.2.0
15 verbose cwd C:\Users\RazorRamone\binance-triangle-arbitrage-master
16 verbose Windows_NT 10.0.19042
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
18 verbose node v14.15.4
19 verbose npm  v6.14.10
20 error code ELIFECYCLE
21 error errno 1
22 error binance-triangle-arbitrage@6.2.0 start: `node src/main/Main.js`
22 error Exit status 1
23 error Failed at the binance-triangle-arbitrage@6.2.0 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by ScuzzyHoulihan** [comment]
Got it working after I created a new API key and allowed more permissions on the key!

**Comment by bmino** [comment]
Awesome, great!
