### ISSUE TITLE
API key

### ISSUE THREAD

**Issue by YuriyTigiev** [bmino/binance-triangle-arbitrage#17]
Hello, 

In which file can I set-up the secret key? Could you provide an example?

**Comment by YuriyTigiev** [comment]
I saw this file, but don't understand where I should put a key and which format. 
Please, write me the exact line number and format.

```
module.exports = {
    // Base symbol which all triangle trades must start and end with
    BASE_SYMBOL: 'BTC',

    INVESTMENT: {
        MIN: 0.1,
        MAX: 0.3,
        STEP: 0.001
    },

    // Order book depth to maintain on each ticker
    // Valid Values: [5, 10, 20, 50, 100, 500, 1000]
    DEPTH_SIZE: 100,

    // Delay (ms) between the opening of each depth websocket
    DEPTH_OPEN_INTERVAL: 50,

    // Delay (ms) after calculations are performed before starting another cycle
    SCAN_DELAY: 200,

    // Number of works processing calculations in the job pool
    CALCULATION_POOL_WORKERS: 1,

    // Interval (ms) at which the HUD is refreshed
    // Disable: set to 0
    HUD_REFRESH_INTERVAL: 200,

    // Number of arbs shown on the HUD
    HUD_ARB_COUNT: 10,

    LOGGING: {
        // Minimum profit required to log an opportunity
        PROFIT_THRESHOLD: 0.00
    }
};

```

**Comment by bmino** [comment]
If you are using the master branch, which I believe you are, there is no file to input a key. The master branch does not yet support order execution and therefore does not need an API key.

What happens when you run `npm start` from inside the project directory?

**Comment by bmino** [comment]
Please confirm which branch you are using.

1. Open a terminal
2. Navigate to the base directory of this project (contains `package.json` and `readme.md`)
3. Type `git status`

**Comment by YuriyTigiev** [comment]
Sorry, my mistake. 
Your software not for trading, only for search optimal pairs. In this case, the script doesn't need api key.

**Comment by bmino** [comment]
Correct. The other branch which supports this will be merged in after a few more additions
