### ISSUE TITLE
About CAP in Config

### ISSUE THREAD

**Issue by jodiekurnia** [bmino/binance-triangle-arbitrage#170]
Hi, 
I kinda confuse about CAP on config,
does CAP max attempt to trade specific opportunity?
let's say ETH->BTC->XMR->ETH, on attempt executing ETH/BTC it's fail, then script kept running just ignore current opportunity, or after successfully execute 1 opportunity the script shutting down? basically if I want it to run 24/7 on a server I need to set CAP to 0?

**Comment by bmino** [comment]
Hey, checkout the configuration [README](https://github.com/bmino/binance-triangle-arbitrage/tree/master/config) where there is descriptions on all the config options.

![image](https://user-images.githubusercontent.com/10902767/125825393-edb65635-706a-47d6-9ab7-f3ee3550ba4e.png)
