### ISSUE TITLE
Profit is always in the negative

### ISSUE THREAD

**Issue by tdev00** [bmino/binance-triangle-arbitrage#172]
Hi @bmino, why is it that the "Profit" is always negative? I've never seen it positive. Where am I going wrong here? I've provided you with the aws specs, my config settings, and a screen capture of the HUD table. Could you provide me with some directions?
Great project @bmino by the way. 

AWS specs:
1) m5n.xlarge
2) Location: Tokyo
3) Amazon Linux 2 AMI (HVM)
4) 64-bit
5) vCPU: 4
6) Memory: 16 GiB
7) Up tp 25 Gigabit

The below is my config:

> "KEYS": {
>        "API": "",
>        "SECRET": ""
>    },
> "INVESTMENT": {
>        "BTC": {
>            "MIN": 0.00148,
>            "MAX": 0.00296891,
>            "STEP": 0.001
>        }
>    },
> "SCANNING": {
>        "DEPTH": 50,
>        "WHITELIST": []
>    },
>    "EXECUTION": {
>        "ENABLED": true,
>        "CAP": 0,
>        "STRATEGY": "linear",
>        "TEMPLATE": ["BUY", "SELL", "SELL"],
>        "FEE": 0.001,
>        "THRESHOLD": {
>            "PROFIT": 0.0002,
>            "AGE": 10
>        }
>    },
> 
>    "HUD": {
>        "ENABLED": true,
>        "ROWS": 20,
>        "REFRESH_RATE": 100
>    },
> "LOG": {
>        "LEVEL": "debug",
>        "PRETTY_PRINT": true,
>        "STATUS_UPDATE_INTERVAL": 1
>    },
> 
>    "WEBSOCKET": {
>        "BUNDLE_SIZE": 1,
>        "INITIALIZATION_INTERVAL": 50
>    },
> 
>    "BINANCE_OPTIONS": {
>        "useServerTime": true,
>        "verbose": true
>      }

The below is the HUD table:
![image](https://user-images.githubusercontent.com/63981572/128937890-5c8c69e6-50b9-4a20-9d38-c62ddc3ca4af.png)

**Comment by bmino** [comment]
Keep in mind this is "risk free profit" and technically shouldn't even exist in the first place assuming an efficient-ish market. You've got specs that make sense but unfortunately it's just too competitive. Folks are out there with direct connections to the Binance exchange with no latency that we just cannot compete with
