### ISSUE TITLE
Real Trading

### ISSUE THREAD

**Issue by 1221328** [bmino/binance-triangle-arbitrage#18]
Hello. Can it perform real trades? If yes, how? I did not find such setting in the conf. file.

**Comment by bmino** [comment]
Hi, the branch [`order-execution`](https://github.com/bmino/binance-triangle-arbitrage/tree/order-execution) does support this and is currently in testing. Follow the readme for further instruction.

**Comment by YuriyTigiev** [comment]
Can we try to use it for testing? with a limited budget - 25$

**Comment by bmino** [comment]
Sure. Be sure your budget is not too small that the minimum order size for any symbol in your pairs is not met

**Comment by 1221328** [comment]
Does it place market orders?

**Comment by 1221328** [comment]
Does the bot already count with the fees in the profit section?

**Comment by bmino** [comment]
It does not. Depending on your discount with Binance you will have to calculate this yourself. A future update will integrate this via a configuration option
