### ISSUE TITLE
Trade not executed

### ISSUE THREAD

**Issue by Fransenson** [bmino/binance-triangle-arbitrage#20]
Hey there!

I just set up version 4.0 and wanted to try the order execution part, so my profit threshold is set as low as 0.025%

The HUD has shown multiple opportunities for several seconds that were above the set profit level, but no order has been executed.

Trading is enabled via the config file.

Do I have to specify anything more within the config to enable trading? 

Execution log is empty.

**Comment by bmino** [comment]
Hey thanks for your interest!

My suspicion is that it is the `TRADING.AGE_THRESHOLD` property is preventing an execution. This value ensures that you are trading with fresh market information and protects you from trading on old, stale market information. When you observe a HUD row where profit meets your criteria, check out the column titled "Age" (which is displayed in seconds not ms) is less than `TRADING.AGE_THRESHOLD`

Each triangle arbitrage needs information from 3 tickers which is provided via websocket. If two of those websockets just updated you now have market depth information that is a few ms old about those two tickers, but the market depth information about that third ticker is perhaps seconds old. The application will calculate expected profit margins using the most recent market depth information known via websocket AND tell you hold old the oldest piece of information is.

**Comment by Fransenson** [comment]
That's a great hint! Gonna look into that. 

May I use this issue to ask another question or shall I open a new one?

Question: 
For the base currency, you have a min, max and step size - how do those work for initial cost calculation? I am just digging through the source, but my node-knowledge is... capable of improvement let's say. :D

**Comment by bmino** [comment]
Sure. Those properties help determine the initial investment for an arbitrage pair.

This is done by starting with the minimal value (in terms of the base symbol) and increasing in increments of the step size until the max value is reached. Each of these investment values is checked for the optimal profit.

There is differing profit values due to how dust works on binance. Triangle arbitrage is profitable because symbol A is converted to B, then C, then back to A. But if there is dust created, then somewhere along those trades some amount WASN'T converted and therefore cannot make a profit via arbitrage.

**Comment by Fransenson** [comment]
Thanks again!

I can leave this open here as I have a relevant question to the title now:

`{"level":"error","time":1549408815285,"msg":"Filter failure: MIN_NOTIONAL","v":1}
`
All my trades die after AB or BC, so I never get back to the main currency. Above is the error from the execution log. 


```
{"level":"info","time":1549408814900,"msg":"Selling 0.002 BTCPAX @ market price","v":1}
{"level":"error","time":1549408815285,"msg":"Filter failure: MIN_NOTIONAL","v":1}
{"level":"info","time":1549415772923,"msg":"Buying 2.92 EOSBTC @ market price","v":1}
{"level":"info","time":1549415773500,"msg":"Selling 2.92 EOSPAX @ market price","v":1}
{"level":"error","time":1549415774089,"msg":"Filter failure: MIN_NOTIONAL","v":1}
{"level":"info","time":1549415780736,"msg":"Selling 0.001 BTCPAX @ market price","v":1}
{"level":"error","time":1549415781036,"msg":"Filter failure: MIN_NOTIONAL","v":1}
{"level":"info","time":1549415783500,"msg":"Buying 10 TUSDBTC @ market price","v":1}
{"level":"info","time":1549415784366,"msg":"Buying 4.42 EOSTUSD @ market price","v":1}
{"level":"error","time":1549415784710,"msg":"Account has insufficient balance for requested action.","v":1}

```

It fails to switch back to BTC and after buying another and another currency is out of balance because everything is stuck in altcoins. Any idea on that?

**Comment by smoochy** [comment]
> But if there is dust created, then somewhere along those trades some amount WASN'T converted and therefore cannot make a profit via arbitrage.

Excuse me, when I chime in here. But I've got a question regarding this.

Lets say during one trade, there was dust left over for an altcoin. And I do not convert that into BNB, but leave it on Binance.

The next time, this coin is bein arbitraged, would the dust be picked up and being tried to be selled? Or will eventually the amount of dust grow over time and needs to be taken care of manually?

**Comment by bmino** [comment]
To answer your question @Fransenson this has to do with the MIN_NOTIONAL filter implemented by Binance. It imposes a minimum order quantity for each ticker. In your case the ticker `BTCPAX` has a MIN_NOTIONAL value of 10 (shown below) and the orders attempted were of quantities 0.001 and then 0.002 which are both below the acceptable value of 10.

To fix this you should increase `CONFIG.INVESTMENT.MIN` to something higher. I will increase the default value in the next release to help others avoid this issue.

```
{
   "symbol": "BTCPAX",
   "status": "TRADING",
   "baseAsset": "BTC",
   "baseAssetPrecision": 8,
   "quoteAsset": "PAX",
   "quotePrecision": 8,
   "orderTypes": [
      "LIMIT",
      "LIMIT_MAKER",
      "MARKET",
      "STOP_LOSS_LIMIT",
      "TAKE_PROFIT_LIMIT"
   ],
   "icebergAllowed": true,
   "filters": [
      {
         "filterType": "PRICE_FILTER",
         "minPrice": "0.01000000",
         "maxPrice": "10000000.00000000",
         "tickSize": "0.01000000"
      },
      {
         "filterType": "PERCENT_PRICE",
         "multiplierUp": "10",
         "multiplierDown": "0.1",
         "avgPriceMins": 5
      },
      {
         "filterType": "LOT_SIZE",
         "minQty": "0.00000100",
         "maxQty": "10000000.00000000",
         "stepSize": "0.00000100"
      },
      {
         "filterType": "MIN_NOTIONAL",
         "minNotional": "10.00000000",
         "applyToMarket": true,
         "avgPriceMins": 5
      },
      {
         "filterType": "ICEBERG_PARTS",
         "limit": 10
      },
      {
         "filterType": "MAX_NUM_ALGO_ORDERS",
         "maxNumAlgoOrders": 5
      }
   ]
}
```

**Comment by bmino** [comment]
Regarding @smoochy calculations for each opportunity are calculated regardless of dust from a previous position. There is not an automated method to clean up dust currently but you can do it through Binance's webapp. The deltas of each balance effected in a trade are displayed in the execution log for reference

**Comment by bmino** [comment]
Does this answer your question @Fransenson?

The bot assumes you are using BNB to pay for trading fees

**Comment by smoochy** [comment]
Is there any way to get in touch with you, like on Telegram or Discord?
The Discord handle in your profile does not exist.

**Comment by bmino** [comment]
The user link is correct. I created a server invite as well
