### ISSUE TITLE
throw er; // Unhandled 'error' event

### ISSUE THREAD

**Issue by SanSan74** [bmino/binance-triangle-arbitrage#21]
Hi!, thanks for sharing your proyect.

(I`m not a developer)

After edit the config.js, and set the API+KEY used to appears an error, 

KEYS: {
        API: undefined,
        SECRET: undefined
    },

I manage to figured out to solve it, I think, with the apostrophe enclosing the API and KEY, this problem is solved, 

KEYS: {
        API: 'XXXXXXXXXX',
        SECRET: 'XXXXXXXX'
    },

but later this error appears

_________________
WARNING! Order execution is enabled!
events.js:183
      throw er; // Unhandled 'error' event
_________________

Any help would be apreciated.
Thanks in advance!

**Comment by bmino** [comment]
Gotcha, I appreciate the perspective on formatting the key and secret. I'll add some human-like output for future users that omit the quotation marks.

For your current issue, would you post all the output from your terminal? I need more context to diagnose what is going on

**Comment by SanSan74** [comment]
Hi bmino,  thanks for the fast response!

I think I found the problem, there is no "/log" directory, if you creat it, works perfect.

Thanks again!

**Comment by bmino** [comment]
Oh no! The app really should check if `/log` exists and create it instead of throwing up.
This will be included in release 4.1.0

It passed my testing because I have `/log` locally. Thanks for the find!
