### ISSUE TITLE
Understanding the Log

### ISSUE THREAD

**Issue by SanSan74** [bmino/binance-triangle-arbitrage#26]
Hi, bmino!

My ignorance is infinite, so first, sorry for the stupid questions.
I'm checking the bot with ETH (balance ETH 0.164 / BNB 0.012) 

{"level":"info","time":"2019-2-7 21:32:01","msg":"Selling 0.13 ETHBTC @ market price","v":1}
{"level":"info","time":"2019-2-7 21:32:01","msg":"Buying 54 GRSBTC @ market price","v":1}
{"level":"info","time":"2019-2-7 21:32:02","msg":"Selling 54 GRSETH @ market price","v":1}
{"level":"info","time":"2019-2-7 21:32:02","msg":"Executed ETH-BTC-GRS position in 1485 ms","v":1}
^
Perfect execution.

{"level":"info","time":"2019-2-7 21:32:02","msg":"BTC delta: 0.000009249999999999994","v":1}
{"level":"info","time":"2019-2-7 21:32:02","msg":"ETH delta: -0.0003470799999999996","v":1}
{"level":"info","time":"2019-2-7 21:32:02","msg":"BNB delta: -0.00396709","v":1}
^
What it showed here?

{"level":"info","time":"2019-2-7 23:57:37","msg":"Buying 96 ADXETH @ market price","v":1}
{"level":"info","time":"2019-2-7 23:57:38","msg":"Selling 96 ADXBNB @ market price","v":1}
{"level":"info","time":"2019-2-7 23:57:38","msg":"Selling 1.79 BNBETH @ market price","v":1}
{"level":"error","time":"2019-2-7 23:57:39","msg":"Account has insufficient balance for requested action.","v":1}
^
This message is given by Binance right?, not enough to pay the fee?
I've check the trading rules of min amounts and meets all the minimal amounts.

BTW, there is a way to make Limit Orders instead of Market?

Thanks in advance

**Comment by bmino** [comment]
The section talking about deltas is giving you a description of exactly what balances changed as a result of the executed trades

The final output about "insufficient balance" is returned by Binance. Either there was not enough BNB to pay the trading fee, or the sell order of ADXBNB did not yield 1.79 BNB as expected

**Comment by SanSan74** [comment]
Excelent thanks!
