### ISSUE TITLE
 Can you ensure that transaction fees are included in the calculations?

### ISSUE THREAD

**Issue by fatihkokay** [bmino/binance-triangle-arbitrage#29]
Can you ensure that transaction fees are included in the calculations?

**Comment by bmino** [comment]
This will be a configurable option in a future release.
For now, take 3x your trading fee and subtract that from the calculated profit.
You should configure `TRADING.PROFIT_THRESHOLD` to be higher to account for this.

So if your trading fee is 0.15% and calculated profit is .67%
```
Fee Percent = 3 x 0.15% = 0.45%
Profit = 0.67% - 0.45% = 0.22%
```

**Comment by bmino** [comment]
Haven't forgotten about ya :)
The next breaking change release will include this feature

**Comment by bmino** [comment]
Still haven't forgotten about this. Wanted to wrap up the execution changes first

**Comment by bmino** [comment]
Introduced in release 5.1.0

**Comment by fatihkokay** [comment]
Thank you I have a few more ideas to improve my system.
