### ISSUE TITLE
support for auto triangular arbitrage

### ISSUE THREAD

**Issue by onthetunnel** [bmino/binance-triangle-arbitrage#3]
Hello Dear, if this project can do :
fully automatic monitoring and auto multiply total amount of btc(binance minimum order limit is 0.001 Btc) and auto order 3 or more profit road(after calc the higher profit of triangular arbitrage pair like :
road1 :BTC-XX1-ETH-BTC 0.02% profit
road2 : BTC-XX2-ETH-BTC 0.018% profit
road3 : BTC-XX3-BNB-BTC 0.011% profit ) on few second and 24/7. running without problem or crash , i will donate 0.005-0.01 BTC , Hope someone can do this work , Thanks You !

**Comment by bmino** [comment]
Thank you for your interest! Execution of identified triangle arbitrage opportunities will be introduced in a future release.

**Comment by onthetunnel** [comment]
Ok Thanks You! nice to hearing this news ! and if this work can complate and working without problem , i will sent the btc to you as i promise ! Thanks You!
