### ISSUE TITLE
 Can we query transactions with more than one coin. BTC ETH, BNB, USDT

### ISSUE THREAD

**Issue by fatihkokay** [bmino/binance-triangle-arbitrage#31]
Can we query transactions with more than one coin. BTC ETH, BNB, USDT

**Comment by bmino** [comment]
Triangle arbitrage requires 3 symbols and 3 tickers.

The first symbol is your base symbol, and the other two can be any symbol. If you wish to restrict this, use the white list config option. 

Does this answer your question?

**Comment by fatihkokay** [comment]
Temel sembolümüzü tek coine değilde işlem yapılabilen BTC,ETH, BNB, USDT coinlerle yapabilirmiyiz.

**Comment by bmino** [comment]
If I understand you correctly, you would like to have multiple options as the base symbol?

**Comment by fatihkokay** [comment]
I've done more arbitrage on the c # via the basic symbol more than one transaction can be captured.

**Comment by clickbrain** [comment]
Would it be possible to just run multiple instances focused on different base coins?

**Comment by clickbrain** [comment]
I am able to run two instances simultaneously - one for BTC and one for USDT. I have not executed trades on either since starting and I am using two separate Binance accounts with different APIs, etc. Do be careful. 
![image](https://user-images.githubusercontent.com/963889/53432434-7fac1980-39c0-11e9-97db-3dfd2da8ebc8.png)

**Comment by bmino** [comment]
Yeah, you can definitely run two instances at once, but you are also sharing system resources between them also.

I see what you are asking for and briefly looked into it awhile ago. The blocker I ran into was how to simply setup configuration to handle the `INVESTMENT.MIN` `INVESTMENT.MAX` and `INVESTMENT.STEP` which need to be defined relative to multiple `INVESTMENT.BASE`(s)
