### ISSUE TITLE
 Although the rate of profit is 6.7, it is able to process losses. How do we get through this?

### ISSUE THREAD

**Issue by fatihkokay** [bmino/binance-triangle-arbitrage#34]
elta: -0.000430570000000019[39m
["2019-3-2 07:31:55"] [32mINFO [39m: [36mBNB delta: -1.0831205399999817[39m
["2019-3-2 07:34:28"] [32mINFO [39m: [36mBuying 116.26 BNBETH @ market price[39m
["2019-3-2 07:34:28"] [32mINFO [39m: [36mBuying 58.04 BNBBTC @ market price[39m
["2019-3-2 07:34:28"] [32mINFO [39m: [36mBuying 7995.8 BATBNB @ market price[39m
["2019-3-2 07:34:28"] [32mINFO [39m: [36mBuying 3991.7 BATBNB @ market price[39m
["2019-3-2 07:34:29"] [32mINFO [39m: [36mSelling 7995 BATETH @ market price[39m
["2019-3-2 07:34:29"] [32mINFO [39m: [36mSelling 3991 BATBTC @ market price[39m
["2019-3-2 07:34:29"] [32mINFO [39m: [36mExecuted ETH-BNB-BAT position in 1643 ms[39m
["2019-3-2 07:34:29"] [32mINFO [39m: [36mExecuted BTC-BNB-BAT position in 1676 ms[39m
["2019-3-2 07:34:30"] [32mINFO [39m: [36mBTC delta: -0.00023083999999995441[39m
["2019-3-2 07:34:30"] [32mINFO [39m: [36mETH delta: -0.05083829999999878[39m
["2019-3-2 07:34:30"] [32mINFO [39m: [36mBNB delta: -0.39297683000000916[39m
["2019-3-2 07:34:30"] [32mINFO [39m: [36mBAT delta: 1.5[39m
["2019-3-2 07:34:30"] [32mINFO [39m: [36mBTC delta: -0.00023083999999995441[39m
["2019-3-2 07:34:30"] [32mINFO [39m: [36mETH delta: -0.05083829999999878[39m
["2019-3-2 07:34:30"] [32mINFO [39m: [36mBNB delta: -0.39297683000000916[39m
["2019-3-2 07:34:30"] [32mINFO [39m: [36mBAT delta: 1.5[39m
["2019-3-2 08:08:47"] [32mINFO [39m: [36mBuying 4.962 ETHBTC @ market price[39m
["2019-3-2 08:08:48"] [32mINFO [39m: [36mBuying 3831 BATETH @ market price[39m
["2019-3-2 08:08:48"] [32mINFO [39m: [36mSelling 3831 BATBTC @ market price[39m
["2019-3-2 08:08:49"] [32mINFO [39m: [36mExecuted BTC-ETH-BAT position in 1796 ms[39m
["2019-3-2 08:08:49"] [32mINFO [39m: [36mBTC delta: 0.0003342199999999962[39m
["2019-3-2 08:08:49"] [32mINFO [39m: [36mETH delta: -0.018137150000001157[39m
["2019-3-2 08:08:49"] [32mINFO [39m: [36mBNB delta: -0.1342032599999925[39m
["2019-3-2 09:19:23"] [32mINFO [39m: [36mSelling 160 BNBBTC @ market price[39m
["2019-3-2 09:19:24"] [31mERROR[39m: [36mAccount has insufficient balance for requested action.[39m

**Comment by kuuulwin** [comment]
The question why this is happening was answered already in another issue by **bmino**.
> 
> What is likely going on is the market shifts before the three trades can be completed. This can be quelled by shrinking the AGE_THRESHOLD so that you are trading with more recent information, but really the problem lies in the time it takes to actually execute three trades in linear fashion.
> 
> You can have market information that is 10ms old, and complete calculations in 15ms, but if it then takes 2000ms to execute the three trades you're in a pickle :(

> To clarify what is going on, the bot calculates that with the current depth cache you should convert currency A into X amount of currency B and then X amount of currency B into Y amount of currency C, but by the time the first or second trade completes, that market information that the initial calculation was done on is stale so you can end up with less than expected
>

**Comment by bmino** [comment]
Hey thanks for your interest!

First of all, if you aren't viewing the logs in a terminal, you should turn off the `LOG.PRETTY_PRINT` config which will print logs as plain text.

The "insufficient balance" message occurs most likely because the market has shifted in the time it took to execute the orders or because you didn't have enough BNB to pay the fees.

The long trade time is something we need a solution for and I am quite up for suggestions
