### ISSUE TITLE
Mirrored Order Execution Loss

### ISSUE THREAD

**Issue by sergioliberton** [bmino/binance-triangle-arbitrage#35]
I have been testing this project for a week, and first I had the following error "Account has insufficient balance for requested action", then I implemented method to apply the rates, and worked, but did not make a profit:
{"level":"info","time":"2019-3-15 00:33:37","msg":"Buying 0.408000000000 ETHBTC @ market price","v":1}
{"level":"info","time":"2019-3-15 00:33:38","msg":"Buying 15409.000000000000 STORMETH @ market price","v":1}
{"level":"info","time":"2019-3-15 00:33:38","msg":"Selling 15409 STORMBTC @ market price","v":1}
{"level":"info","time":"2019-3-15 00:33:39","msg":"15409","v":1}
{"level":"info","time":"2019-3-15 00:33:39","msg":"[object Object]","v":1}
{"level":"info","time":"2019-3-15 00:33:39","msg":"Executed BTC-ETH-STORM position in 1616 ms","v":1}
{"level":"info","time":"2019-3-15 00:33:39","msg":"BTC delta: -0.0000997800000000007","v":1}
{"level":"info","time":"2019-3-15 00:33:39","msg":"ETH delta: 0.00057895","v":1}
{"level":"info","time":"2019-3-15 00:33:39","msg":"BNB delta: -0.008126319999999992","v":1}
{"level":"error","time":"2019-3-15 00:33:40","msg":"Cannot exceed execution cap of 1 execution","v":1}

I would like to know if you have had reports of someone who has made a profit from this system, and if so, what configurations the person used, since I can not do it, I know about the issue of runtime, so I wonder if anyone could find one configuration that can make profit, thank you.

**Comment by bmino** [comment]
Hey, thanks for your interest in this project!

I'm not sure what you mean by "then I implemented method to apply the rates" but that error you are seeing about insufficient balances is unfortunately normal. It stems from the low latency it takes to execute three trades. The app can calculate profits in maybe 20 ms, but then it takes almost 1000 ms to execute the first trade and more time to execute the next two trades. By the time the first trade completes, too much time has passed and the market has shifted.

This is a big problem and one I am looking for a solution to. The best answer is parallel execution which eliminates this issue completely, but requires holding balances of multiple commodities.

**Comment by kuuulwin** [comment]
Hi **bmino**
I noticed that depending on market conditions linear executions with the same pairs end up with different results.
For example, if 
**bc / ab < ca** 
then the trades will be profitable.
But if 
**bc / ab > ca** 
you get a loss. That's why there is no consistency when you leave the script run by itself.
I can clarify with examples if needed.

**Comment by bmino** [comment]
I am quite happy to discuss further! Feel free to post an example because I'm not yet following your point.

You can also find me on discord directly

**Comment by bmino** [comment]
Upon further investigation and conversation with @kuuulwin it appears that mirrored execution pairs (ie A>B>C>A vs A>C>B>A) are not identical. Seeing as mirrored pairs are being filtered out since f47c36a83bea760d2fed0dbb28b8b8e664de7f0a, they will need to be re-added.

This will increase the calculation cycle time, but will ensure that all arbs are being investigated

**Comment by sergioliberton** [comment]
Hi Mino.
That's what I imagined, I've been doing some tests and I really do not have time to execute the order, I think it's because there are several robots running to get these opportunities. I really want this project to work, I'm going to do tests and I'll tell you if I can get something, and I'll keep up with your modifications, let's make this arbitration work out :)

**Comment by bmino** [comment]
You and I are at a disadvantage competing for arbitrage opportunities. There are other players with hardware beyond what I can comprehend, less latency, and direct connections to the exchange. We're fighting an uphill battle, but dang if I don't believe in at least the software!
