### ISSUE TITLE
triangle is cant be completed

### ISSUE THREAD

**Issue by insayd10** [bmino/binance-triangle-arbitrage#36]
execution.log : 
`["2019-3-19 04:26:03"] [32mINFO [39m: [36mBuying 55.555 SKYBTC @ market price[39m
["2019-3-19 04:26:04"] [32mINFO [39m: [36mSelling 55.555 SKYETH @ market price[39m
["2019-3-19 04:26:04"] [31mERROR[39m: [36mAccount has insufficient balance for requested action.[39m
["2019-3-19 04:26:05"] [32mINFO [39m: [36mBTC delta: -0.015064409999999999[39m
["2019-3-19 04:26:05"] [32mINFO [39m: [36mSKY delta: 55.499445[39m
["2019-3-19 04:50:36"] [31mERROR[39m: [36mCannot exceed execution cap of 1 execution[39m
`

**Comment by insayd10** [comment]
buys 55.499 coin but try sells 55.555 sky

**Comment by bmino** [comment]
I am aware of the "Account has insufficient balance for requested action. It has been raised a few times by users of the program.

I started a designated issue thread to track this at #37
