### ISSUE TITLE
Account has insufficient balance for requested action

### ISSUE THREAD

**Issue by bmino** [bmino/binance-triangle-arbitrage#37]
**Description:**
This issue stems from the high latency it takes to execute three trades. The app can calculate profits in maybe 20ms, but then it takes almost 1000ms to execute the first trade and more time to execute the next two trades. By the time the first trade completes, too much time has passed and the market has shifted.

You can have market information that is 10ms old, and complete calculations in 20ms, but if it then takes 2500ms to execute the three trades, you are in a pickle :(

**More Technical Description:**
The bot calculates that with the current depth cache you should convert currency A into X amount of currency B and then X amount of currency B into Y amount of currency C, but by the time the first or second trade completes, that market depth cache information which the initial calculation was based on is stale so you can end up with less B or C than expected.

This error will occur when trying to perform the second or third leg of the triangle arbitrage.

**Solutions:**
* Use the `TRADING.EXECUTION_STRATEGY` of `"parallel"`
* Help me figure out a better alternative!

**Comment by kuuulwin** [comment]
Is there a way to switch trading in absolute values to percents?

Right now the program calculates the how much cryptocurrency to buy and sell in absolute values but by the time they’re executed the market shifts and you have your orders stuck midway through.  
 
What if you can execute trades using percents: you buy 100% (available from your balance) of coin B then sell 100% of your coin B for coin C and last you buy coin A with 100% of coin C. 

You won’t need MIN, MAX and STEP anymore. Most crypto platforms do it. But I don’t know how difficult that may be for you to implement into your source code.

As for runtime I heard about a function called KeepAlive. I think it revolves around the idea to keep websockets always open. But the after effects of it are a mystery to me. I can look more into it.
<img width="992" alt="Screen Shot 2019-03-19 at 10 54 57" src="https://user-images.githubusercontent.com/47988777/54589168-f7a4b700-4a35-11e9-83a6-4cefc0581fe7.png">
It can be found in node-binance-api.js after the initial install of the script.

This is all I have for now. Don't know if it helps.

**Comment by bmino** [comment]
**As per the keepOpen option of websockets:**
This is currently implemented. All market cache data is being populated from websockets

**As per trading on a percent basis:**
Interesting! This isn't something I have considered yet. If all symbols involved are traded at 100% except for the base symbol this would work I think. However, it couldn't be a backup option ie "trade the calculated amount unless an insufficient balance error occurs, then trade x amount" because that would involve *extra* http calls which is the issue in the first place.

**Comment by kuuulwin** [comment]
Perhaps orders will not get stuck if you have some spare change in your wallet such as BTC and ETH.
When the market shifts and there is not enough coin to finish the triangle, the script can take some from your wallet.
For example, we have A, B, C cryptocurrencies. Just have 95% of A and 5% of B. It's usually the fractions of a cent that get the triangle stuck.

**Comment by bmino** [comment]
Yup, that would avoid the insufficient balance error @kuuulwin, but there is still a large window between calculation and when the final execution completes. That calculation has a lower degree of accuracy as time passes

**Comment by bmino** [comment]
Piggy backing off your idea however

If the calculation says `x` amount A will be converted into `y` amount of B, we can assume something like 0.95 * `y` is actually obtained of B where the 0.95 is configurable depending on volatility and market execution times.

**Pros:**
* Lessen the likelihood of the insufficient balance error
* Configurable depending on volatility, preference, etc.

**Cons:**
* Leads to small quantities of balance accumulating in random symbols
* Will not convert 100% of A through the cycle leading to less profit
* Does not guarantee to avoid the insufficient balance error

**Comment by kuuulwin** [comment]
Another thought. Can the AB amount be fixed when executing arbitrage? Because when you get an arbitrage opportunity with a profit of 0.3% it's usually have a weird number like 23.384723 USDT, so the program starts executing AB with 23.3145688 USDT, but Binance rounds up the numbers quite often that's why you have insufficient balance. 

I noticed that while setting up a lot of STEPS between MIN and MAX. But then, you have increased amount of calculations which affects the execution time.

I hope the general idea is clear but I can elaborate if needed.

**Comment by kuuulwin** [comment]
Actually, BNB, ETH and BTC round up numbers differently I don't know how you can adjust trading amounts to all of them.

**Comment by kuuulwin** [comment]
Another idea, perform a calculation after the first or before the last trade.
In A - B - C you calculate according to the results of the first BUY or SELL (after AB executed before BC)
In A - C - B you calculate according to the results of second BUY or SELL (after BC executed before AB)
You said calculations might take about 20 ~ 30 ms that's not too bad of a loss.

**Comment by kuuulwin** [comment]
I doesn't make any sense. I have split the balance into two parts, the first one failed and second succeeded. 
<img width="387" alt="Screen Shot 2019-04-03 at 13 06 19" src="https://user-images.githubusercontent.com/47988777/55471045-8ce8a380-5611-11e9-87fb-e73c69761113.png">

**Comment by kuuulwin** [comment]
It looks like whether you want it or not you can't make a buy or a sell using the **exact** values as in MIN, MAX and STEP. Binance will round them up either way. So after the first or before last trade, the triangle is recalculated for the new purchase or sale price and no extra http calls as I understand. 
If this idea won't work I can keep thinking about something else.

**Comment by bmino** [comment]
I like where your thought process is going!

If I read your idea correctly, you are suggesting once a determined amount of A is successfully converted into some amount of B, we then do another calculation to determine how much C we should expect from that amount of B?

The simpler approach would be to simply look at the exact amount of B we actually obtained. This can perhaps be done by:

1. Subscribing to a user's balance updates and calculating a delta on previous / new balance for B
2. Subscribing to a user's executionReport or something similar to view actual received quantity from a market order. This is by far preferable if possible

**Comment by kuuulwin** [comment]
Yes, how much C we can buy with already bought or sold B (for A-B-C) and how much A we can buy with already bought or sold B (for A-C-B)
I see sometimes that values in execution report and actual trades don't align perfectly. But it can dismissed for now. Either way, a correct quantity need to obtained and the general idea I believe is faster is better.

**Comment by kuuulwin** [comment]
Sometimes I overcomplicate things. But yes, the general idea is to do a balance check and recalculate based on what you got from the previous trade/trades.

I have another idea. When selecting an amount to trade with the script usually underBuys. For example, if you start execution with 40 USDT, you trade will rounded up to 39+ change. Is there a way to let the script overBuy with 40+ change then you have more room for the next trade.

<img width="870" alt="Screen Shot 2019-04-06 at 21 23 25" src="https://user-images.githubusercontent.com/47988777/55673570-42d21d00-58b2-11e9-9b4c-c231d6c041b1.png">
Here the script could have bought 0.005866 and still fit in 30.2 USDT

Or overBuy 0.005867 and go over 30.2 by 0.00114521 which is a tenth fraction of a cent.
I have no clue whether this is going good, bad or work at all but no recalculation will be needed.

**Comment by bmino** [comment]
Looks like Binance has changed their api for market orders since the last time I looked. They now provide two golden parameters called `executedQty` and `cummulativeQuoteQty` which will provide us the the exact quantity of both symbols involved in the transaction.

After each leg in linear execution, we can look at the amount of the previous symbol received or spent, recalculate based on current market conditions if necessary, and then convert 100% of that into the next symbol. No need for insufficient balance errors!

It also allows us to convert as much of A as possible into B -> C -> A with minimal dust being generated in intermediate symbols.

**Comment by moonorblue** [comment]
> Looks like Binance has changed their api for market orders since the last time I looked. They now provide two golden parameters called `executedQty` and `cummulativeQuoteQty` which will provide us the the exact quantity of both symbols involved in the transaction.
> 
> After each leg in linear execution, we can look at the amount of the previous symbol received or spent, recalculate based on current market conditions if necessary, and then convert 100% of that into the next symbol. No need for insufficient balance errors!
> 
> It also allows us to convert as much of A as possible into B -> C -> A with minimal dust being generated in intermediate symbols.

So this issue might be resolved by these parameters ?  This issue still occurs in current version, might be fixed in next release ?
Thank you for such good bot

**Comment by bmino** [comment]
I'm testing it locally, but the next release will likely include these changes!

**Comment by sergioliberton** [comment]
All right?
I would like to know if there is anything new in relation to linear linearity, is someone making a profit or still has a problem that has already changed the market?
Thank you.

**Comment by bmino** [comment]
The recalculation logic is looking good, but there is still the occasional "account has insufficient balance" error. We're going for 100% bug squashing here though!

My other idea is to provide a config option that locks the three trade methods to BUY, SELL, SELL. This guarantees that we know the quantity of conversion in the second and third trade and can safely assume that we are even or slightly overestimating the initial investment quantity of A

**Comment by bmino** [comment]
Release 5.0.0 should fix this issue. If you continue to experience this issue using the latest release and settings, please open a new issue
