### ISSUE TITLE
about parallel arb 

### ISSUE THREAD

**Issue by insayd10** [bmino/binance-triangle-arbitrage#38]
Watching 2 relationship(s) is not sufficient to engage in triangle arbitrage

```
    "INVESTMENT": {
        "BASE": "BTC",
        "MIN": 0.005,
        "MAX": 0.013,
        "STEP": 0.005
    },

    "TRADING": {
        "ENABLED": true,
        "EXECUTION_STRATEGY": "parallel",
        "EXECUTION_CAP": 3,
        "PROFIT_THRESHOLD": 0.3,
        "AGE_THRESHOLD": 300,
        "WHITELIST": ["BTC", "ETH", "BNB"]
    },
```

whats wrong with me

**Comment by bmino** [comment]
This appears to be a bug!

I'll have a fix out soon with some improved logging to help clarify when a config check fails

**Comment by bmino** [comment]
Please confirm if this issue is resolved

**Comment by insayd10** [comment]
will try :( but loss big, I'm scared

**Comment by bmino** [comment]
You can run with the same setup with `TRADING.ENABLED` set to `false` to simulate a run, but without actually making any trades.

**Comment by insayd10** [comment]
That isss, thank you bmino
