### ISSUE TITLE
sells at a loss: S

### ISSUE THREAD

**Issue by insayd10** [bmino/binance-triangle-arbitrage#39]
linear setting sells loss

**Comment by bmino** [comment]
Hey can you please provide some more context to the issue you are seeing?

Not issue #37 which explains why it is difficult to see profitable executions using a linear execution strategy due to the long latency of executing trades

**Comment by insayd10** [comment]
```
["2019-3-20 12:59:06"] [32mINFO [39m: [36mBuying 8.89 EOSBTC @ market price[39m
["2019-3-20 12:59:06"] [32mINFO [39m: [36mSelling 8.89 EOSETH @ market price[39m
["2019-3-20 12:59:07"] [32mINFO [39m: [36mSelling 0.235 ETHBTC @ market price[39m
["2019-3-20 12:59:08"] [32mINFO [39m: [36mExecuted BTC-EOS-ETH position in 1921 ms[39m
["2019-3-20 12:59:08"] [32mINFO [39m: [36mBTC delta: -0.00003840000000000093[39m
["2019-3-20 12:59:08"] [32mINFO [39m: [36mETH delta: 0.0010154699999999905[39m
["2019-3-20 12:59:08"] [32mINFO [39m: [36mBNB delta: -0.004834840000000007[39m
["2019-3-20 18:18:23"] [31mERROR[39m: [36mCannot exceed execution cap of 1 execution[39m
["2019-3-20 20:39:57"] [32mINFO [39m: [36mBuying 0.29 ETHBTC @ market price[39m
```

**Comment by insayd10** [comment]
another bad think: 
`["2019-3-20 23:45:12"] [31mERROR[39m: [36mCannot exceed execution cap of 1 execution[39m
["2019-3-21 04:18:25"] [32mINFO [39m: [36mBuying 16.89 GXSBTC @ market price[39m
["2019-3-21 04:18:26"] [32mINFO [39m: [36mSelling 16.89 GXSETH @ market price[39m
["2019-3-21 04:18:26"] [32mINFO [39m: [36mSelling 0.146 ETHBTC @ market price[39m
["2019-3-21 04:18:27"] [31mERROR[39m: [36mAccount has insufficient balance for requested action.[39m
["2019-3-21 04:18:27"] [32mINFO [39m: [36mBTC delta: -0.0049893[39m
["2019-3-21 04:18:27"] [32mINFO [39m: [36mETH delta: 0.1449162[39m
["2019-3-21 04:18:27"] [32mINFO [39m: [36mBNB delta: -0.00200763[39m
`

**Comment by bmino** [comment]
**First Example:**
It appears that all three trades were executed successfully and the result was a net loss.

**Second Example:**
Looks like two trades were executed successfully, and the third failed due to an insufficient balance of ETH.

Both are examples of correct calculations, but the market shifts too much in the ~2000ms it took to execute the trades. This is documented in #37 and will likely happen when running via a linear execution strategy until we can come up with a solution
