### ISSUE TITLE
Doesn't work in windows?

### ISSUE THREAD

**Issue by Tencru** [bmino/binance-triangle-arbitrage#4]
I'm running it but doesn't appear coins

**Comment by Tencru** [comment]
[https://i.gyazo.com/6b37ef78cd4a54ef85574de047c470ee.jpg](url)

**Comment by bmino** [comment]
Hey Tencru, I'm not sure what you mean by "doesn't appear coins" but based on your provided image, it appears you did not install dependencies.

Install dependencies by running this in the project root directory:
```
npm install
```

**Comment by Tencru** [comment]
oh boy, i had installed in the old TriangularArbitrage-master andI thought it was not necessary to install it again xD

That's what i mean when i said doesn't appear coins 

https://i.gyazo.com/b3678e90ee185c7f42bb5816ab396aaa.jpg

**Comment by bmino** [comment]
Yup, you should do an 'npm install' after each pull if you are unsure. Does that solve your issue?

**Comment by Tencru** [comment]
Just updated the files with your last updated and it's working now: https://i.gyazo.com/a0d2aed8b7d55caf3895265811321964.jpg

What are you doing with the bot right now? improving it to be faster?

I would like to tell you a way to get more out of the bot but I would like to tell you in privately, could you tell me a way to contact?

discord, email, telegram, something like this?

**Comment by bmino** [comment]
Hit me up on discord if you wanna chat
User: Dorito#8415
