### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by Memoi** [bmino/binance-triangle-arbitrage#48]
Hi,

Nothing happen, I executed the code on Git bash (windows), npm version 6.7, node version 11.8

![1](https://user-images.githubusercontent.com/35448059/56092036-25efa800-5eb7-11e9-9ffe-39a2abd4b2ab.png)

![2](https://user-images.githubusercontent.com/35448059/56092039-2720d500-5eb7-11e9-90b6-56a0bb284092.png)

My conf :

{

    "KEYS": {
        "API": "xxx",
        "SECRET": "xxx"
    },

    "INVESTMENT": {
        "BASE": "BTC",
        "MIN": 0.011,
        "MAX": 0.018,
        "STEP": 0.005
    },

    "TRADING": {
        "ENABLED": false,
        "EXECUTION_STRATEGY": "parallel",
        "EXECUTION_CAP": 1,
        "PROFIT_THRESHOLD": 0.3,
        "AGE_THRESHOLD": 300,
        "WHITELIST": ["BTC","ETH","BNB","USDT","EOS"]
    },

    "HUD": {
        "ENABLED": true,
        "ARB_COUNT": 10
    },

    "LOG": {
        "LEVEL": "info",
        "PRETTY_PRINT": true
    },

    "DEPTH": {
        "SIZE": 50,
        "INITIALIZATION_INTERVAL": 50
    },

    "CALCULATION_COOLDOWN": 100

}

There is nothing in the logs in info mode.

Log in debug mode :

["2019-4-14 12:16:15"] DEBUG: Operating System: Windows_NT
["2019-4-14 12:16:15"] DEBUG: Cores Speeds: [3500,3500,3500,3500,3500,3500,3500,3500] MHz
["2019-4-14 12:16:19"] DEBUG: Completed 12/12 (100.0%) calculations in 2 ms
["2019-4-14 12:16:19"] DEBUG: Completed 12/12 (100.0%) calculations in 1 ms
["2019-4-14 12:16:19"] DEBUG: Completed 12/12 (100.0%) calculations in 1 ms
["2019-4-14 12:16:19"] DEBUG: Completed 12/12 (100.0%) calculations in 1 ms
["2019-4-14 12:16:19"] DEBUG: Completed 12/12 (100.0%) calculations in 1 ms
...

Thanks for your help

**Comment by Memoi** [comment]
It's working with PowerShell... strange

**Comment by Davee-io** [comment]
Same error on xfce terminal
-Linux Mint 19.1 (Tessa) xfce

**Comment by bmino** [comment]
The terminal that started the app shouldn't show anything after the stat overview printout (unless you have the HUD turned on).

If you turn the log level to "trace" you will see the calculation time of each cycle in the performance log. The execution log will only show logging when a position is executed

@Memoi I think you have resolved your issue right?

@Davee-io What is your issue more precisely? Are you saying nothing is being logged, or the app is not running?

**Comment by bmino** [comment]
edit: I see you have opened a new issue. Let's discuss there unless memoi wishes to reopen this
