### ISSUE TITLE
Timestamp for this request was 1000ms ahead of the server's time

### ISSUE THREAD

**Issue by x0racle** [bmino/binance-triangle-arbitrage#51]
caseless:
   Caseless {
     dict:
      { 'content-type': 'application/json;charset=utf-8',
        'transfer-encoding': 'chunked',
        connection: 'close',
        date: 'Sat, 27 Apr 2019 16:04:19 GMT',
        server: 'nginx',
        'x-mbx-used-weight': '5',
        'strict-transport-security': 'max-age=31536000; includeSubdomains',
        'x-frame-options': 'SAMEORIGIN',
        'x-xss-protection': '1; mode=block',
        'x-content-type-options': 'nosniff',
        'content-security-policy': "default-src 'self'",
        'x-content-security-policy': "default-src 'self'",
        'x-webkit-csp': "default-src 'self'",
        'cache-control': 'no-cache, no-store, must-revalidate',
        pragma: 'no-cache',
        expires: '0',
        'x-cache': 'Error from cloudfront',
        via:
         '1.1 b3229c68bc96ea68371695efdc615317.cloudfront.net (CloudFront)',
        'x-amz-cf-id': '6ZN6xzHzS2z0CqYUSoLeymcLKSwx3pEd3xRfZSbcorGHjvTK8daGJg==' } },
  body:
   `{"code":-1021,"msg":"Timestamp for this request was 1000ms ahead of the server's time."}` }

**Comment by bmino** [comment]
This is a check put in place from Binance to ensure that an api request doesn't lag too bad. Sync your system clock and it should go away.

If it doesn't, there is an additional option that can be used to sync each request with the api server.

**Comment by Davee-io** [comment]
-"Sync your system clock and it should go away."

That was the issue .. Thanks so much for your quick reply!
Have a nice time :)

**Comment by bmino** [comment]
Sure thing!

**Comment by danielj86** [comment]
Im having the same problem, my clock is synced.
@bmino What is the other otption you mention to sync each request?

**Comment by bmino** [comment]
My suggestion is to add this fourth config option as a binance argument in the file src/main/Main.js

```javascript
binance.options({
    APIKEY: CONFIG.KEYS.API,
    APISECRET: CONFIG.KEYS.SECRET,
    test: !CONFIG.TRADING.ENABLED,
    useServerTime: true
});
```

Even if this fixes the issue, will you please post the error if you can still replicate it? And for reference your operating system as well

**Comment by danielj86** [comment]
Im using Windows 10, the problem is was that my the auto-sync with Internet time was off.
After enabling it and forcing sync the problem solved.
