### ISSUE TITLE
Not working..

### ISSUE THREAD

**Issue by Davee-io** [bmino/binance-triangle-arbitrage#52]
![Screenshot_2019-04-27_21-24-03](https://user-images.githubusercontent.com/43140394/56854211-28301880-6933-11e9-921f-34def99cb076.png)

Operating System:
- Linux Mint 19.1 (Tessa) xfce

**Comment by bmino** [comment]
You need to set a values on your investment min max and step

**Comment by Davee-io** [comment]
So, the account need to have balance up in order to test the bot?

**Comment by Memoi** [comment]
Fyi I didn't found a fix on Git bash, it's working only in PowerShell on my Windows OS

**Comment by bmino** [comment]
Notice the output "Optimization ticks: NaN"

This means that no calculations are being made when the bot is running. You need to set values for your investment min max and step. Because your TRADING.ENABLED is set to false, no trades will actually be made

**Comment by Davee-io** [comment]
Yep, balance needed for run the script.

**Comment by bmino** [comment]
Haha yeah, you will need balances to trade, but if your goal is to observe the market (via the HUD perhaps) then you do not need a balance.

I don't see any errors in the first screenshot. What did you want to happen that did not?
