### ISSUE TITLE
Trading Methods

### ISSUE THREAD

**Issue by pfeiflelukas** [bmino/binance-triangle-arbitrage#53]
Just a question about the two trading methods available

```
Linear - Three trades are executed sequentially with each being initiated after the first has completed
Parallel - Three trades are executed asynchronously with each being initiated at the same time
```

Isn't Linear the only way the arbitrage can work as the orders need to be run in order? such as AB to BC to CA

With parallel they are all executed at the same time. But wouldn't that mean you need at least some value in each asset?

Is the cause of Parallel trading more trades but at a higher risk?

**Comment by bmino** [comment]
Yup parallel trading requires that you have a balance of all symbols in your whitelist

**Comment by pfeiflelukas** [comment]
Yeah makes sense, awesome thanks for the confirmation.
