### ISSUE TITLE
New API key

### ISSUE THREAD

**Issue by Memoi** [bmino/binance-triangle-arbitrage#55]
Hi,
since Binance deleted all api key, my new API Key seams to not work :

> node src/main/Main.js

WARNING! Order execution is enabled!

[ 'balanceData error', {} ]
IncomingMessage {
  _readableState:
   ReadableState {
     objectMode: false,
     highWaterMark: 16384,
     buffer: BufferList { head: null, tail: null, length: 0 },
     length: 0,
     pipes: null,
     pipesCount: 0,
     flowing: true,
     ended: true,
     endEmitted: true,
     reading: false,
     sync: false,
     needReadable: false,
     emittedReadable: false,
     readableListening: false,
     resumeScheduled: false,
     paused: false,
     emitClose: true,
     autoDestroy: false,
     destroyed: false,
     defaultEncoding: 'utf8',
     awaitDrain: 0,
     readingMore: false,
     decoder: null,
     encoding: null },
  readable: false,
  _events:
   [Object: null prototype] {
     end: [ [Function: responseOnEnd], [Function] ],
     close: [ [Function], [Function] ],
     data: [Function],
     error: [Function] },
  _eventsCount: 4,
  _maxListeners: undefined,
  socket:

**Comment by bmino** [comment]
Yup, Binance posted a message about this and sent an email I think. You have to log into the binance web console and create new api credentials

**Comment by bmino** [comment]
1) Log in
2) https://www.binance.com/userCenter/myAccount.html
3) Enable API
4) Follow steps to create a new api key and secret

**Comment by Memoi** [comment]
I did and it's not working

**Comment by bmino** [comment]
What is the error you are seeing? I don't see an error message in the stack you posted

**Comment by Memoi** [comment]
The problem is fix by itslef, may be a problem on Binance side
