### ISSUE TITLE
Why most profit is negative number

### ISSUE THREAD

**Issue by georgezouq** [bmino/binance-triangle-arbitrage#6]
I think negative profit means the price within 3 currency has gap, Is that mean If we transform currency order, the profit will be positive？

![screen shot 2018-07-03 at 11 33 49 am](https://user-images.githubusercontent.com/5990860/42197356-fcdfa3da-7eb4-11e8-99b1-b7b3c9c001a8.png)

**Comment by bmino** [comment]
Thanks for your question! Negative numbers under the profit section mean exactly what you might expect. They indicate that if you convert currency A to B, then B to C, and then C to A, you will incur a net loss.

This application shows the most profitable opportunities, but in a generally efficient market, there will not none or few opportunities that are profitable. Also keep in mind this does not account for the 0.05% trading fees

**Comment by georgezouq** [comment]
@bmino Thank you!
