### ISSUE TITLE
How to enable "read only" version with no MIN and no MAX?

### ISSUE THREAD

**Issue by marsrobertson** [bmino/binance-triangle-arbitrage#60]
```
Error: An available balance of 0.015 BTC is required to satisfy your INVESTMENT.MIN configuration
    at checkBalances (/Users/ms/Stuff/binance-triangle-arbitrage/src/main/Main.js:173:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

```
Error: An available balance of 0.035 BTC is required to satisfy your INVESTMENT.MAX configuration
    at checkBalances (/Users/ms/Stuff/binance-triangle-arbitrage/src/main/Main.js:178:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

I just don't have any coins on that exchange, would like to run the bot anyway. So far commented out the lines that are complaining: https://github.com/bmino/binance-triangle-arbitrage/blob/0dae169110d20133603331a0371c6647cb1b6e9e/src/main/Main.js#L170-L179

**Comment by bmino** [comment]
Great point. Perhaps those pre-runtime checks should only be executed if TRADING.ENABLED is true?

**Comment by steveeakin** [comment]
I like that.

I build in DEMO mode in my fork that somewhat accomplishes this.

**Comment by bmino** [comment]
I've got those changes introduced in the develop branch for the next release :)

**Comment by bmino** [comment]
Please check out release 5.2.0 and verify this issue is resolved
