### ISSUE TITLE
With so many pair and potential arbitrage opportunities - why show negative profit?

### ISSUE THREAD

**Issue by marsrobertson** [bmino/binance-triangle-arbitrage#62]
![image](https://user-images.githubusercontent.com/44369284/59570208-77b9d780-908c-11e9-9b45-ab87a0f44de8.png)

**Comment by bmino** [comment]
Not sure I completely understand your question, but the HUD shows an overview of the best opportunities at the time. Wouldn't it be great if there were always risk free profitable opportunities?

The reality is that arbitrage is tough to find, and rare to occur

**Comment by marsrobertson** [comment]
OK, thanks!

These are the best pairs.

Because your code is open source, no wonder why all opportunities are pretty much gone.

Cheers.
