### ISSUE TITLE
Websockets close and then crash

### ISSUE THREAD

**Issue by pfeiflelukas** [bmino/binance-triangle-arbitrage#64]
Hey everyone,

Is anyone else having issues with the websockets closing after about 2 minutes?
Everything works without issue and with no errors displaying on startup.

I have already tried fresh OS install and installation on NPM and Node

Anyone experienced the same?

**Comment by bmino** [comment]
I have not experienced this issue. Every so often a few websockets will disconnect and is typically caused by high cpu usage that bottlenecked the machine or a network cutout.

Would you please post a screenshot of the error for documentation

**Comment by pfeiflelukas** [comment]
<img width="960" alt="error" src="https://user-images.githubusercontent.com/20794390/60379576-086abd00-9a68-11e9-8307-114fd84a5e90.PNG">

It is running on a Pi 3 so the cores jump around a bit, but previously i have had no issues with running this. Not too sure what has changed. I checked the power supply and cable to the Pi and both are good.

**Comment by pfeiflelukas** [comment]
<img width="428" alt="error2" src="https://user-images.githubusercontent.com/20794390/60380175-baf44d00-9a73-11e9-984d-ee0656ae51c5.PNG">

**Comment by bmino** [comment]
Your specs look competent to run the bot, but it's typically the internet cutting out or dropping that will lead to reconnecting websockets

I haven't been able to replicate that EAI_AGAIN error. Not sure about that

**Comment by pfeiflelukas** [comment]
#65 Looks like the same issue.

I also put the Raspberri Pi on a DMZ and issue persists. Pretty sure it isn't my network

**Comment by pfeiflelukas** [comment]
i think i may have found the solution. It does appear to be a performance issue with Raspberry Pi's, specifically CPU.

Reducing the HUD to 10, Depth Size to 20, Initialisation_interval to 75 and lastly calculation_cooldown to 750 greatly reduces CPU overhead.

So far working well

**Comment by bmino** [comment]
Increasing cooldown will definitely alleviate stress on your cpu as that gives times in between each calculation cycle (cpu intensive) to recover and process other tasks. The initialization interval won't really affect performance, but if the websockets disconnect very quickly upon starting, increasing this could help

**Comment by kuuulwin** [comment]
> Increasing cooldown will definitely alleviate stress on your cpu as that gives times in between each calculation cycle (cpu intensive) to recover and process other tasks. The initialization interval won't really affect performance, but if the websockets disconnect very quickly upon starting, increasing this could help

kewl, but what happens if the arbitrage opportunity is found during a cooldown, like between the calculation cycles?

**Comment by bmino** [comment]
Arbitrage opportunities exist many times throughout the day (in real time). The challenge is to identify and act on them as soon as possible. With a higher calculation cooldown window, calculation cycles are performed less often and you run the risk of missing too many opportunities. But with a short cooldown, your cpu won't have enough free cycles. This is a tradeoff and the reason why the cooldown time is provided as a configuration parameter
