### ISSUE TITLE
Error after attempting to open websockets

### ISSUE THREAD

**Issue by NoctisNebula** [bmino/binance-triangle-arbitrage#65]
Firstly thanks a lot for sharing your project with us,this is my first time trying to use it..
I tried to run it both in ubuntu and on windows machine,I have plenty of resources and I am using the exact versions of nodejs and npm you are suggesting,however in both cases I get a fatal error..
Please check the log attached
[log.txt](https://github.com/bmino/binance-triangle-arbitrage/files/3342374/log.txt)

 for more details,
Thanks!!

**Comment by pfeiflelukas** [comment]
@NoctisNebula Do websockets keep closing after about 2 minutes, this then leads to a fatal crash?

**Comment by kuuulwin** [comment]
I get myself an error message after the script runs for a while. 
<img width="694" alt="Screen Shot 2019-06-30 at 08 33 03" src="https://user-images.githubusercontent.com/47988777/60393114-cbaace80-9b18-11e9-9d2e-2be162688097.png">

**Comment by pfeiflelukas** [comment]
look in issue #64 i believe i solved the issue

**Comment by kuuulwin** [comment]
Well, the previous versions run without any errors with the same settings. 
So, in the current one something might be amiss.

**Comment by NoctisNebula** [comment]
Thank you for your suggestions guys! However I think this problem is different than the one in issue #64, I am not getting the RangeError/stack size error,and the websockets are not opening at all it wents into the error every time...Anyway I tried the fix he suggested on #64,but the situation remains the same.. I have no idea about previous versions tho this is the first version I'm trying..

**Comment by bmino** [comment]
Thank you for the kind words and support!

Glad to see those issues resolved. For reference I typically run and test on Ubuntu and all seems to be working well for me. What do you mean by "bugged" @NoctisNebula, A screenshot would be awesome

**Comment by NoctisNebula** [comment]
> 
> 
> Thank you for the kind words and support!
> 
> Glad to see those issues resolved. For reference I typically run and test on Ubuntu and all seems to be working well for me. What do you mean by "bugged" @NoctisNebula, A screenshot would be awesome

Certainly,I would do anything to help,the "bug" I mentioned is actually just a visual bug,I was only able to see the Trade/Profit/AB Age tabs in cmd interface,however that is insignificant,the stats are showing while I m using cmder so everything seems to be fine.
Print attached for the refference.
Thanks again for your amazing work! 
Hopefully in the future we could help you more with this project,and at least donate when we can,cheers & have a brilliant week!

**Comment by bmino** [comment]
Yikes! Yeah the first screenshot appears to be missing width. But I've seen windows prompts block the max width allowed. The second screenshot looks rough. Seems like the character encodings used to format text aren't supported/recognized by that terminal.

I appreciate your patience and contributions!
