### ISSUE TITLE
Error opening websocket (Error: ETIMEDOUT)

### ISSUE THREAD

**Issue by Y0sh1dk** [bmino/binance-triangle-arbitrage#69]
I am currently having problems getting the bot started, it is running inside a Ubuntu VM but also had the same problem on a windows machine. Sometimes the error is ETIMEDOUT and other times ESOCKETTIMEDOUT.

Error: ETIMEDOUT
    at Timeout._onTimeout (/home/test/binance-triangle-arbitrage/node_modules/request/request.js:849:19)
    at ontimeout (timers.js:482:11)
    at tryOnTimeout (timers.js:317:5)
    at Timer.listOnTimeout (timers.js:277:5)

npm ERR! Linux 4.18.0-15-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "start"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! binance-triangle-arbitrage@5.2.1 start: `node src/main/Main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the binance-triangle-arbitrage@5.2.1 start script 'node src/main/Main.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the binance-triangle-arbitrage package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node src/main/Main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs binance-triangle-arbitrage
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls binance-triangle-arbitrage
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/test/binance-triangle-arbitrage/npm-debug.log

**Comment by bmino** [comment]
Hey, I would recommended using the versions of node and npm specified in the project readme. It appears you are using 8.10.0 (node) and 3.5.2 (npm) which are dated

**Comment by Y0sh1dk** [comment]
Thanks for the reply, I have updated both npm and nodeJS to the correct versions and am still having trouble getting it started. 

:~$ npm -v
6.10.0

:~$ node -v
v11.10.0


binance-triangle-arbitrage@5.2.1 start /home/test/binance-triangle-arbitrage
> node src/main/Main.js

Successfully pinged the Binance api in 266 ms
Found 519/568 currently trading tickers
Found 227 triangular relationships
Checking configuration ...
Opening 519 depth websockets ...
/home/test/binance-triangle-arbitrage/node_modules/node-binance-api/node-binance-api.js:1835
                            if (err) throw err;
                                     ^

Error: ETIMEDOUT
    at Timeout._onTimeout (/home/test/binance-triangle-arbitrage/node_modules/request/request.js:849:19)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7) {
  code: 'ETIMEDOUT',
  connect: true
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! binance-triangle-arbitrage@5.2.1 start: `node src/main/Main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the binance-triangle-arbitrage@5.2.1 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/test/.npm/_logs/2019-07-16T02_00_08_925Z-debug.log

**Comment by bmino** [comment]
Okay, can I see your config please? My suspicion is that too many websockets are being opened in quick succession and your hardware is being overwhelmed

**Comment by Y0sh1dk** [comment]
Sure, I don't believe I have changed anything to the config except added my API. The VM is running on 4 cores and 4gb of RAM So I doubt it is a hardware issue. Is it possibly a network config/router issue?

Thanks


{

    "KEYS": {
        "API": "##### ",
        "SECRET": "#####"
    },

    "INVESTMENT": {
        "BASE": "BTC",
        "MIN": 0.015,
        "MAX": 0.035,
        "STEP": 0.005
    },

    "TRADING": {
        "ENABLED": false,
        "EXECUTION_STRATEGY": "linear",
        "EXECUTION_TEMPLATE": ["BUY", "SELL", "SELL"],
        "EXECUTION_CAP": 1,
        "TAKER_FEE": 0.00,
        "PROFIT_THRESHOLD": 0.30,
        "AGE_THRESHOLD": 300,
        "WHITELIST": []
    },

    "HUD": {
        "ENABLED": true,
        "ARB_COUNT": 10
    },

    "LOG": {
        "LEVEL": "info",
        "PRETTY_PRINT": true
    },

    "DEPTH": {
        "SIZE": 50,
        "PRUNE": false,
        "INITIALIZATION_INTERVAL": 75
    },

    "CALCULATION_COOLDOWN": 250

}

**Comment by bmino** [comment]
Yeah, I agree that looks fine. I have experienced that after restarting the app too many times in quick succession and there was api restrictions buried in libraries. Waiting for some time and then restarting the bot alleviated that for me until I learned the exact api weight that starting the bot at various config settings would require.
