### ISSUE TITLE
Profit Calculation

### ISSUE THREAD

**Issue by GRTTX** [bmino/binance-triangle-arbitrage#70]
The bot doesn't find any trades ive had it on for 2 days and the profit % just keeps saying about -0.5% - -0.8%. On every market

**Comment by bmino** [comment]
Keep in mind that risk free profit does not occur very often. Also note that the HUD only displays a snapshot of the values being calculated. Many more are being run through calculation loops. What are your config settings?

**Comment by acongtsai** [comment]
["7/16/2019, 19:51:26"] [32mINFO [39m: [36mAttempting to execute USDT-ETC-USDC with an age of 185 ms and expected profit of 0.3227%[39m
["7/16/2019, 19:51:26"] [32mINFO [39m: [36mBuying 0.33 ETCUSDT @ market price[39m
["7/16/2019, 19:51:27"] [31mERROR[39m: [36mFilter failure: MIN_NOTIONAL[39m
["7/16/2019, 19:51:29"] [32mINFO [39m: [36mAttempting to execute USDT-ETC-USDC with an age of -765 ms and expected profit of 0.3905%[39m
["7/16/2019, 19:51:29"] [32mINFO [39m: [36mBuying 0.33 ETCUSDT @ market price[39m
["7/16/2019, 19:51:30"] [31mERROR[39m: [36mFilter failure: MIN_NOTIONAL[39m
["7/16/2019, 19:51:30"] [32mINFO [39m: [36mAttempting to execute USDT-ETC-USDC with an age of 31 ms and expected profit of 0.3462%[39m
["7/16/2019, 19:51:30"] [32mINFO [39m: [36mBuying 0.33 ETCUSDT @ market price[39m
["7/16/2019, 19:51:30"] [31mERROR[39m: [36mFilter failure: MIN_NOTIONAL[39m
["7/16/2019, 19:51:33"] [32mINFO [39m: [36mAttempting to execute USDT-ETC-USDC with an age of -846 ms and expected profit of 0.3342%[39m
["7/16/2019, 19:51:33"] [32mINFO [39m: [36mBuying 0.33 ETCUSDT @ market price[39m
["7/16/2019, 19:51:33"] [31mERROR[39m: [36mFilter failure: MIN_NOTIONAL[39m
["7/16/2019, 19:51:34"] [32mINFO [39m: [36mAttempting to execute USDT-ETC-USDC with an age of -209 ms and expected profit of 0.3342%[39m
["7/16/2019, 19:51:34"] [32mINFO [39m: [36mBuying 0.33 ETCUSDT @ market price[39m
["7/16/2019, 19:51:34"] [31mERROR[39m: [36mFilter failure: MIN_NOTIONAL[39m
["7/16/2019, 19:51:35"] [32mINFO [39m: [36mAttempting to execute USDT-ETC-USDC with an age of -431 ms and expected profit of 0.3646%[39m
["7/16/2019, 19:51:35"] [32mINFO [39m: [36mBuying 0.33 ETCUSDT @ market price[39m
["7/16/2019, 19:51:35"] [31mERROR[39m: [36mFilter failure: MIN_NOTIONAL[39m
["7/16/2019, 19:51:36"] [32mINFO [39m: [36mAttempting to execute USDT-ETC-USDC with an age of -844 ms and expected profit of 0.3526%[39m
["7/16/2019, 19:51:36"] [32mINFO [39m: [36mBuying 0.33 ETCUSDT @ market price[39m
["7/16/2019, 19:51:36"] [31mERROR[39m: [36mFilter failure: MIN_NOTIONAL[39m
["7/16/2019, 19:51:37"] [32mINFO [39m: [36mAttempting to execute USDT-ETC-USDC with an age of -37 ms and expected profit of 0.4120%[39m
["7/16/2019, 19:51:37"] [32mINFO [39m: [36mBuying 0.33 ETCUSDT @ market price[39m
["7/16/2019, 19:51:37"] [31mERROR[39m: [36mFilter failure: MIN_NOTIONAL[39m
["7/16/2019, 19:51:38"] [32mINFO [39m: [36mAttempting to execute USDT-ETC-USDC with an age of -401 ms and expected profit of 0.4120%[39m
["7/16/2019, 19:51:38"] [32mINFO [39m: [36mBuying 0.33 ETCUSDT @ market price[39m
["7/16/2019, 19:51:38"] [31mERROR[39m: [36mFilter failure: MIN_NOTIONAL[39m
["7/16/2019, 19:51:38"] [32mINFO [39m: [36mAttempting to execute USDT-ETC-USDC with an age of -714 ms and expected profit of 0.3492%[39m
["7/16/2019, 19:51:38"] [32mINFO [39m: [36mBuying 0.33 ETCUSDT @ market price[39m
["7/16/2019, 19:51:39"] [31mERROR[39m: [36mFilter failure: MIN_NOTIONAL[39m
["7/16/2019, 19:51:39"] [32mINFO [39m: [36mAttempting to execute USDT-ETC-USDC with an age of -1012 ms and expected profit of 0.3609%[39m
["7/16/2019, 19:51:39"] [32mINFO [39m: [36mBuying 0.33 ETCUSDT @ market price[39m
["7/16/2019, 19:51:39"] [31mERROR[39m: [36mFilter failure: MIN_NOTIONAL[39m
["7/16/2019, 19:51:40"] [32mINFO [39m: [36mAttempting to execute USDT-ETC-USDC with an age of -393 ms and expected profit of 0.3609%[39m
["7/16/2019, 19:51:40"] [32mINFO [39m: [36mBuying 0.33 ETCUSDT @ market price[39m
["7/16/2019, 19:51:40"] [31mERROR[39m: [36mFilter failure: MIN_NOTIONAL[39m
["7/16/2019, 19:51:40"] [32mINFO [39m: [36mAttempting to execute USDT-ETC-USDC with an age of -628 ms and expected profit of 0.3526%[39m
["7/16/2019, 19:51:40"] [32mINFO [39m: [36mBuying 0.33 ETCUSDT @ market price[39m
["7/16/2019, 19:51:41"] [31mERROR[39m: [36mFilter failure: MIN_NOTIONAL[39m
["7/16/2019, 19:51:41"] [32mINFO [39m: [36mAttempting to execute USDT-ETC-USDC with an age of -857 ms and expected profit of 0.3408%[39m
["7/16/2019, 19:51:41"] [32mINFO [39m: [36mBuying 0.33 ETCUSDT @ market price[39m
["7/16/2019, 19:51:41"] [31mERROR[39m: [36mFilter failure: MIN_NOTIONAL[39m
["7/16/2019, 19:51:42"] [32mINFO [39m: [36mAttempting to execute USDT-ETC-USDC with an age of -115 ms and expected profit of 0.3408%[39m
["7/16/2019, 19:51:42"] [32mINFO [39m: [36mBuying 0.33 ETCUSDT @ market price[39m
["7/16/2019, 19:51:42"] [31mERROR[39m: [36mFilter failure: MIN_NOTIONAL[39m
["7/16/2019, 19:51:43"] [32mINFO [39m: [36mAttempting to execute USDT-ETC-USDC with an age of -345 ms and expected profit of 0.3408%[39m
["7/16/2019, 19:51:43"] [32mINFO [39m: [36mBuying 0.33 ETCUSDT @ market price[39m
["7/16/2019, 19:51:43"] [31mERROR[39m: [36mFilter failure: MIN_NOTIONAL[39m
["7/16/2019, 19:51:44"] [32mINFO [39m: [36mAttempting to execute USDT-ETC-USDC with an age of -504 ms and expected profit of 0.3578%[39m
["7/16/2019, 19:51:44"] [32mINFO [39m: [36mBuying 0.33 ETCUSDT @ market price[39m
["7/16/2019, 19:51:44"] [31mERROR[39m: [36mFilter failure: MIN_NOTIONAL[39m
["7/16/2019, 19:51:44"] [32mINFO [39m: [36mAttempting to execute USDT-ETC-USDC with an age of 193 ms and expected profit of 0.3646%[39m
["7/16/2019, 19:51:44"] [32mINFO [39m: [36mBuying 0.33 ETCUSDT @ market price[39m
["7/16/2019, 19:51:44"] [31mERROR[39m: [36mFilter failure: MIN_NOTIONAL[39m
["7/16/2019, 19:51:49"] [32mINFO [39m: [36mAttempting to execute USDT-ETC-USDC with an age of -838 ms and expected profit of 0.3918%[39m
["7/16/2019, 19:51:49"] [32mINFO [39m: [36mBuying 0.33 ETCUSDT @ market price[39m
["7/16/2019, 19:51:49"] [31mERROR[39m: [36mFilter failure: MIN_NOTIONAL[39m
["7/16/2019, 19:51:50"] [32mINFO [39m: [36mAttempting to execute USDT-ETC-USDC with an age of -61 ms and expected profit of 0.3969%[39m
["7/16/2019, 19:51:50"] [32mINFO [39m: [36mBuying 0.33 ETCUSDT @ market price[39m
["7/16/2019, 19:51:50"] [31mERROR[39m: [36mFilter failure: MIN_NOTIONAL[39m
["7/16/2019, 19:51:51"] [32mINFO [39m: [36mAttempting to execute USDT-ETC-USDC with an age of -326 ms and expected profit of 0.3969%[39m
["7/16/2019, 19:51:51"] [32mINFO [39m: [36mBuying 0.33 ETCUSDT @ market price[39m
["7/16/2019, 19:51:51"] [31mERROR[39m: [36mFilter failure: MIN_NOTIONAL[39m
["7/16/2019, 19:51:53"] [32mINFO [39m: [36mAttempting to execute USDT-ETC-USDC with an age of -937 ms and expected profit of 0.3748%[39m
["7/16/2019, 19:51:53"] [32mINFO [39m: [36mBuying 0.33 ETCUSDT @ market price[39m
["7/16/2019, 19:51:53"] [31mERROR[39m: [36mFilter failure: MIN_NOTIONAL[39m
["7/16/2019, 19:51:54"] [32mINFO [39m: [36mAttempting to execute USDT-ETC-USDC with an age of -226 ms and expected profit of 0.3748%[39m
["7/16/2019, 19:51:54"] [32mINFO [39m: [36mBuying 0.33 ETCUSDT @ market price[39m
["7/16/2019, 19:51:54"] [31mERROR[39m: [36mFilter failure: MIN_NOTIONAL[39m
["7/16/2019, 19:51:55"] [32mINFO [39m: [36mAttempting to execute USDT-ETC-USDC with an age of -449 ms and expected profit of 0.3155%[39m
["7/16/2019, 19:51:55"] [32mINFO [39m: [36mBuying 0.33 ETCUSDT @ market price[39m
["7/16/2019, 19:51:55"] [31mERROR[39m: [36mFilter failure: MIN_NOTIONAL[39m

can't execute even though the profit has been set 0.30%

my config

"INVESTMENT": {
        "BASE": "USDT",
        "MIN": 2,
        "MAX": 2,
        "STEP": 2
    },

    "TRADING": {
        "ENABLED": true,
        "EXECUTION_STRATEGY": "linear",
        "EXECUTION_TEMPLATE": ["BUY", "BUY", "SELL"],
        "EXECUTION_CAP": 0,
        "TAKER_FEE": 0.00,
        "PROFIT_THRESHOLD": 0.30,
        "AGE_THRESHOLD": 300,
        "WHITELIST": []
    },

    "HUD": {
        "ENABLED": true,
        "ARB_COUNT": 5
    },

    "LOG": {
        "LEVEL": "info",
        "PRETTY_PRINT": true
    },

    "DEPTH": {
        "SIZE": 50,
        "PRUNE": false,
        "INITIALIZATION_INTERVAL": 100
    },

    "CALCULATION_COOLDOWN": 250

**Comment by acongtsai** [comment]
sometimes the first purchase is successfully resumed for the second purchase always fails because the first decimal difference in purchase has been due to fee fees for example when the first purchase usdt / eth 0.157 there is a fee discount of 0.10% then the value is only 0.155 for the second purchase eth / edr eth number enter by bot is 0.157 even though the value is only 0.155 here it often happens the second purchase execution fails because of this decimal value difference and there is more if there is a crypto value that can be sold or bought decimal round crypto occurs 0.00156789 sometimes can only be sold or bought 0.00156 so the remaining 0.00000789 cannot be included

**Comment by bmino** [comment]
@acongtsai Are you paying for fees via BNB? This is a requirement for the bot to work successfully.

Please open a new issue as this sounds like a different topic than what @GRTTX is asking.

**Comment by angelassets** [comment]
Hi,
All my trades are returning a loss... what would be an Ideal setting? Any guide? Presently using default settings...
