### ISSUE TITLE
Has anyone made a profit?

### ISSUE THREAD

**Issue by sergioliberton** [bmino/binance-triangle-arbitrage#74]
Sorry to return to this subject, but I was fine without following the updates of your program, at the time could not make a profit, wanted to know if today has any configuration that made a profit? Thank you.

**Comment by bmino** [comment]
I've made some small profits here and there. It's not super common but that's the nature of an efficient market

**Comment by bazan101** [comment]
I'm sorry but I disagree I really think that the crypto market is ABSOLUTLY not effiicient so many triangle should be profitable especially if you use crypto with a lots of pairs like BTC,BNB or ETH.

**Comment by bazan101** [comment]
I spent time reading your comment about profit and I'm trying to think that you are probably right we are not alone trying to use this kind of trading technics so maybe yes it is hard to get results.

**Comment by bmino** [comment]
@sergioliberton if you had better results with a prior version of the bot, you can revert to any release that better suits your needs. I'd be happy to help you with the git commands if desired.

@bazan101 there is definitely inefficiencies in the market or the bot would never pick up profits. But as you noted, detecting and executing on these scenarios in a quick enough timeframe is difficult. Hence the development of this software to tackle that challenge. I joke sometimes that a whale is using my software on a warehouse of machines wired directly into an exchange
