### ISSUE TITLE
Config Option

### ISSUE THREAD

**Issue by morison-krw** [bmino/binance-triangle-arbitrage#76]
Ok, I understand.

You have a depth size config which ranges from 5 to 100. But do you think it would help, if you can also choose how far in the order book you can go for calculation purposes.

Meaning that if your first order is a BUY, I can base my calculations on the average of three ASK prices or two, five and etc. as well as other legs in the triangle. Thank you!

<img width="435" alt="61743915-cef34c00-ad9e-11e9-94a1-3b97debaaeb8" src="https://user-images.githubusercontent.com/53236898/61990426-3c2a0a00-b049-11e9-86be-0400bb052686.png">

**Comment by bmino** [comment]
If I understand what you are asking, you want to limit the depth used in an order book when calculating profits?

ie you might track a depth of 100 but only want to use the first 8 depths for calculation?

**Comment by morison-krw** [comment]
Yes, calculate profits according to specific depths. Maybe not the average, but skipping first price, second price and start calculations with the third one, or skipping the first and start calculations with the second one, in each leg.

The idea is to filter through the stray prices (too low or too high), people put in the order book, god knows why, and to focus more on the average that moves the market. 

I have profited in trades where first prices are not far from the next ones in the order book.

**Comment by bmino** [comment]
Okay, I thought you wanted to go a maximum of X depths into the order book when calculating, but I'm understanding now that you want to skip X initial depths and see if the calculations still show profitable?

Ignoring cheaper prices would decrease the margins available and lessen the opportunities detected. Those margins are already so slim by handicapping yourself, I suspect you will price yourself out of the game entirely.
