### ISSUE TITLE
Error: ETIMEDOUT

### ISSUE THREAD

**Issue by vfelletti** [bmino/binance-triangle-arbitrage#79]
Hey man, tks for sharing your project!

I have a problem to solve when I run npm start:
Error: ETIMEDOUT
    at Timeout._onTimeout (C:\Users\victo\OneDrive\Documentos\Projects\triangle_arb\binance-triangle-arbitrage-master\node_modules\request\request.js:849:19)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! binance-triangle-arbitrage@5.2.2 start: `node src/main/Main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the binance-triangle-arbitrage@5.2.2 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

I already update node and npm, reinstalled the project, but the issue persists.
node v11.15.0
npm v6.10.3

{

    "KEYS": {
        "API": ****
        "SECRET": ****
    },

    "INVESTMENT": {
        "BASE": "BTC",
        "MIN": 0.0012,
        "MAX": 0.0020,
        "STEP": 0.0001
    },

    "TRADING": {
        "ENABLED": true,
        "EXECUTION_STRATEGY": "linear",
        "EXECUTION_TEMPLATE": ["BUY", "SELL", "BUY"],
        "EXECUTION_CAP": 0,
        "TAKER_FEE": 0.00,
        "PROFIT_THRESHOLD": 0.30,
        "AGE_THRESHOLD": 300,
        "WHITELIST": []
    },

    "HUD": {
        "ENABLED": true,
        "ARB_COUNT": 5
    },

    "LOG": {
        "LEVEL": "info",
        "PRETTY_PRINT": true
    },

    "DEPTH": {
        "SIZE": 50,
        "PRUNE": false,
        "INITIALIZATION_INTERVAL": 100
    },

    "CALCULATION_COOLDOWN": 250

}

Can you help me? Tks again!

**Comment by bmino** [comment]
Glad you appreciate the project!

If you wouldn't mind, let's discuss this in #77 as that is the same root issue
