### ISSUE TITLE
Error: Watching 0 triangular relationships is not sufficient to engage in triangle arbitrage

### ISSUE THREAD

**Issue by noahwalugembe** [bmino/binance-triangle-arbitrage#80]
am getting this{Error: Watching 0 triangular relationships is not sufficient to engage in triangle arbitrage}

What are the minimum configurations and BNB Balance that can help see some arbitrage operations

**Comment by bmino** [comment]
Any base can be used (BNB in this case), but you need to ensure there are enough relationships involving BNB to complete a triangle.

example: 3 tickers BNB-B, B-C, and C-BNB where B and C must exist are be trading

**Comment by noahwalugembe** [comment]
Currently my BNC base is 0.6 BNC is it much more less get any arbitage opportunities or I need more BNC balance and is so what is the minimum balance is need for me to start with

**Comment by bmino** [comment]
My mistake, I assumed you meant BNB. You are indeed trying to use BNC (Bionic) as your base?

There might not be enough related tickers to BNC for it to be viable in triangle arbitrage.

**Comment by noahwalugembe** [comment]
Thanks @bmino bmino it is now fixed but the table is not displayed properly 
![image](https://user-images.githubusercontent.com/27782388/63577454-1b48cc00-c597-11e9-8e27-8237db667434.png)

**Comment by bmino** [comment]
Okay, at first look it appears you need more screen. The font config for the HUD needs at least a certain width/height in terms of pixels. Drag that window diagonally to be bigger.
