### ISSUE TITLE
I have failed to run this code on Ubuntu amazon web service{I need some help}{I have attached a log file }

### ISSUE THREAD

**Issue by noahwalugembe** [bmino/binance-triangle-arbitrage#82]
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/home/ubuntu/.nvm/versions/node/v12.9.1/bin/node',
1 verbose cli   '/home/ubuntu/.nvm/versions/node/v12.9.1/bin/npm',
1 verbose cli   'start'
1 verbose cli ]
2 info using npm@6.10.2
3 info using node@v12.9.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle binance-triangle-arbitrage@5.2.2~prestart: binance-triangle-arbitrage@5.2.2
6 info lifecycle binance-triangle-arbitrage@5.2.2~start: binance-triangle-arbitrage@5.2.2
7 verbose lifecycle binance-triangle-arbitrage@5.2.2~start: unsafe-perm in lifecycle true
8 verbose lifecycle binance-triangle-arbitrage@5.2.2~start: PATH: /home/ubuntu/.nvm/versions/node/v12.9.1/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/home/ubuntu/binance-triangle/node_modules/.bin:/home/ubuntu/.nvm/versions/node/v12.9.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle binance-triangle-arbitrage@5.2.2~start: CWD: /home/ubuntu/binance-triangle
10 silly lifecycle binance-triangle-arbitrage@5.2.2~start: Args: [ '-c', 'node src/main/Main.js' ]
11 silly lifecycle binance-triangle-arbitrage@5.2.2~start: Returned: code: 1  signal: null
12 info lifecycle binance-triangle-arbitrage@5.2.2~start: Failed to exec start script
13 verbose stack Error: binance-triangle-arbitrage@5.2.2 start: `node src/main/Main.js`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/home/ubuntu/.nvm/versions/node/v12.9.1/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:326:16)
13 verbose stack     at EventEmitter.emit (events.js:209:13)
13 verbose stack     at ChildProcess.<anonymous> (/home/ubuntu/.nvm/versions/node/v12.9.1/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:209:13)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid binance-triangle-arbitrage@5.2.2
15 verbose cwd /home/ubuntu/binance-triangle
16 verbose Linux 4.15.0-1044-aws
17 verbose argv "/home/ubuntu/.nvm/versions/node/v12.9.1/bin/node" "/home/ubuntu/.nvm/versions/node/v12.9.1/bin/npm" "start"
18 verbose node v12.9.1
19 verbose npm  v6.10.2
20 error code ELIFECYCLE
21 error errno 1
22 error binance-triangle-arbitrage@5.2.2 start: `node src/main/Main.js`
22 error Exit status 1
23 error Failed at the binance-triangle-arbitrage@5.2.2 start script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by bmino** [comment]
I don't notice anything obvious from that log. What are you doing to start the app? Did you use the steps listed at https://github.com/bmino/binance-triangle-arbitrage#deployment

**Comment by joma512900** [comment]
@bmino friend what is your email? I need to contact you for a project
