### ISSUE TITLE
need advise

### ISSUE THREAD

**Issue by noahwalugembe** [bmino/binance-triangle-arbitrage#83]
If i have 10 BNB How best can i configure the part blow starting with BNB as the base

  "INVESTMENT": {
        "BASE": "BTC",
        "MIN": 0.015,
        "MAX": 0.035,
        "STEP": 0.005
    },

**Comment by bmino** [comment]
If you want your base currency to be BNB, then set the "BASE" property to BNB. Referring to the [readme](https://github.com/bmino/binance-triangle-arbitrage/tree/master/config) might also be helpful in describing what each property in the config does.

Something like this:
```
"INVESTMENT": {
    "BASE": "BNB",
    "MIN": 5,
    "MAX": 9,
    "STEP": 0.5
}
```

**Comment by noahwalugembe** [comment]
Description: Market taker fee (percent) I cant understand this
