### ISSUE TITLE
calculation cooldown

### ISSUE THREAD

**Issue by aherco** [bmino/binance-triangle-arbitrage#84]
what is the purpose of setting a calculation cooldown? what would happen if i just set it to 0?

**Comment by bmino** [comment]
Please refer to the [readme](https://github.com/bmino/binance-triangle-arbitrage/tree/master/config) for descriptions of all the config properties. I would recommend that you don't change anything without understanding what it does first.

When starting the app, requests must be made to acquire a baseline for each symbol. If too many requests are made in quick succession:

1. You will exceed the api limitations and get an api ban
2. Your cpu will choke processing the responses

**Comment by aherco** [comment]
is there a race condition? would lowering it decrease the time between finding an arbitrage opportunity and executing a trade? and if so, what are the effects of the incorrectly processed results that the cooldown mitigates?

**Comment by bmino** [comment]
There cannot be a race condition when using the calculation cooldown setting because it is a delay used AFTER each cycle is completed. Setting this to zero would have your cpu constantly working (and potentially lock out other tasks) but might be okay depending on your thread count etc.
