### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by 1221328** [bmino/binance-triangle-arbitrage#9]
npm ERR! Linux 4.15.0-23-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "live"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code ELIFECYCLE
npm ERR! binance-triangle-arbitrage@3.4.0 live: `node src/main/Main.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the binance-triangle-arbitrage@3.4.0 live script 'node src/ma                                                                                                             in/Main.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the binance-triangle-arbi                                                                                                             trage package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node src/main/Main.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs binance-triangle-arbitrage
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls binance-triangle-arbitrage
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /root/binance-triangle-arbitrage/npm-debug.log

**Comment by bmino** [comment]
I am also running on Ubuntu 18.04 with:
npm: 6.3.0
node: 9.11.2

Are you still experiencing this issue?

**Comment by 1221328** [comment]
I’ll try it again and let you know.

**Comment by 1221328** [comment]
brew install node
W: be careful as root.
Don't run this as root!

**Comment by 1221328** [comment]
root@TEST:~# git clone https://github.com/bmino/binance-triangle-arbitrage.git
Cloning into 'binance-triangle-arbitrage'...
remote: Counting objects: 785, done.
remote: Compressing objects: 100% (7/7), done.
remote: Total 785 (delta 0), reused 7 (delta 0), pack-reused 778
Receiving objects: 100% (785/785), 329.78 KiB | 1.11 MiB/s, done.
Resolving deltas: 100% (413/413), done.
root@TEST:~# npm install
npm WARN enoent ENOENT: no such file or directory, open '/root/package.json'
npm WARN root No description
npm WARN root No repository field.
npm WARN root No README data
npm WARN root No license field.

**Comment by bmino** [comment]
Okay so it appears that your first error was installing node which it looks like you have resolved. Your second issue was attempting to install dependencies with `npm install` which has to be run from the root of the project and I think you solved this as well.

Your remaining problem is a lack of configuration. This can be resolved by following the instructions in the readme under the "Configuration" section:

"All configuration is done inside the /config directory. To setup your configuration for the first time, duplicate each of the *.example files, remove the ".example" extension, and fill in the appropriate information."

Let me know if you need further assistance!
