### ISSUE TITLE
How can I fix this? mpino.final with prettyPrint does not support flushing

### ISSUE THREAD

**Issue by chalitgubkb** [bmino/binance-triangle-arbitrage#91]
Because it doesn't work. When encountering this problem, the program quits immediately.

["2020-3-13 11:38:51"] [32mINFO [39m:
["2020-3-13 11:38:52"] [41mFATAL[49m: [36mCannot exceed user defined execution cap of 1 executions[39m
[1584074332515] [33mWARN [39m: [36mpino.final with prettyPrint does not support flushing[39m

**Comment by bmino** [comment]
Good catch, you are experience two things:

1. You have a configured execution cap of 1, and the program is respecting that and shutting down after completing one arbitrage triangle.
2. The logging framework is choking on a formatting issue. This appears to be a known bug via pino (our logging framework) and I will address it tonight in an update.

Is your concern the log error about flushing, or the bot exiting after completing one execution?
