### ISSUE TITLE
Question: What country would you suggest if we deploy this on an Amazon instance?

### ISSUE THREAD

**Issue by daryl552007** [bmino/binance-triangle-arbitrage#97]
Question: What country would you suggest if we deploy this on an Amazon instance?

Will the server location even matter or do you have any recommendations on how address lag time?

**Comment by bmino** [comment]
I definitely recommend running this with as little latency as possible.

The last time I researched, Binance was supposedly hosting their servers in the Hong Kong region via AWS

**Comment by daryl552007** [comment]
Thanks Bmino,

I keep getting this websocket closed then reconnecting .. what could be causing this?

![image](https://user-images.githubusercontent.com/64083391/82201218-9c6c9e00-9932-11ea-8f7b-afcf80c8bcf1.png)

**Comment by bmino** [comment]
It could be from a number of things:

* Unstable internet connection
* Overwhelmed cpu
* Too many open connections

Please open a new issue so we can more accurately track each question/issue on its own
